/**
 * This file is generated by the Angular 2 template compiler.
 * Do not edit.
 */
 /* tslint:disable */

import * as import0 from '@angular/core/src/render/api';
import * as import1 from '@angular/core/src/linker/view';
import * as import2 from '@angular/core/src/linker/element';
import * as import3 from './collision-table.component';
import * as import4 from '@angular/core/src/linker/view_utils';
import * as import5 from '@angular/core/src/di/injector';
import * as import6 from '@angular/core/src/linker/view_type';
import * as import7 from '@angular/core/src/change_detection/change_detection';
import * as import8 from '@angular/core/src/metadata/view';
import * as import9 from '@angular/core/src/linker/component_factory';
var renderType_CollisionTableComponent_Host:import0.RenderComponentType = (null as any);
class _View_CollisionTableComponent_Host0 extends import1.AppView<any> {
  _el_0:any;
  /*private*/ _appEl_0:import2.AppElement;
  _CollisionTableComponent_0_4:import3.CollisionTableComponent;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement) {
    super(_View_CollisionTableComponent_Host0,renderType_CollisionTableComponent_Host,import6.ViewType.HOST,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import2.AppElement {
    this._el_0 = this.selectOrCreateHostElement('col-table',rootSelector,(null as any));
    this._appEl_0 = new import2.AppElement(0,(null as any),this,this._el_0);
    var compView_0:any = viewFactory_CollisionTableComponent0(this.viewUtils,this.injector(0),this._appEl_0);
    this._CollisionTableComponent_0_4 = new import3.CollisionTableComponent();
    this._appEl_0.initComponent(this._CollisionTableComponent_0_4,[],compView_0);
    compView_0.create(this._CollisionTableComponent_0_4,this.projectableNodes,(null as any));
    this.init([].concat([this._el_0]),[this._el_0],[],[]);
    return this._appEl_0;
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import3.CollisionTableComponent) && (0 === requestNodeIndex))) { return this._CollisionTableComponent_0_4; }
    return notFoundResult;
  }
}
function viewFactory_CollisionTableComponent_Host0(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement):import1.AppView<any> {
  if ((renderType_CollisionTableComponent_Host === (null as any))) { (renderType_CollisionTableComponent_Host = viewUtils.createRenderComponentType('',0,import8.ViewEncapsulation.None,[],{})); }
  return new _View_CollisionTableComponent_Host0(viewUtils,parentInjector,declarationEl);
}
export const CollisionTableComponentNgFactory:import9.ComponentFactory<import3.CollisionTableComponent> = new import9.ComponentFactory<import3.CollisionTableComponent>('col-table',viewFactory_CollisionTableComponent_Host0,import3.CollisionTableComponent);
const styles_CollisionTableComponent:any[] = ['.glyphicon[_ngcontent-%COMP%]{\n        display: block;\n        text-align: center;\n        margin: auto;\n        vertical-align: middle;\n        line-height: normal;\n    }\n    .container[_ngcontent-%COMP%]{\n        padding-bottom: 5%;\n    }'];
var renderType_CollisionTableComponent:import0.RenderComponentType = (null as any);
class _View_CollisionTableComponent0 extends import1.AppView<import3.CollisionTableComponent> {
  _el_0:any;
  _text_1:any;
  _el_2:any;
  _text_3:any;
  _el_4:any;
  _text_5:any;
  _el_6:any;
  _text_7:any;
  _el_8:any;
  _text_9:any;
  _el_10:any;
  _text_11:any;
  _text_12:any;
  _el_13:any;
  _text_14:any;
  _text_15:any;
  _text_16:any;
  _el_17:any;
  _text_18:any;
  _text_19:any;
  _el_20:any;
  _text_21:any;
  _el_22:any;
  _text_23:any;
  _el_24:any;
  _text_25:any;
  _el_26:any;
  _text_27:any;
  _el_28:any;
  _text_29:any;
  _text_30:any;
  _el_31:any;
  _text_32:any;
  _text_33:any;
  _el_34:any;
  _text_35:any;
  _text_36:any;
  _el_37:any;
  _text_38:any;
  _text_39:any;
  _el_40:any;
  _text_41:any;
  _text_42:any;
  _el_43:any;
  _text_44:any;
  _text_45:any;
  _text_46:any;
  _el_47:any;
  _text_48:any;
  _el_49:any;
  _text_50:any;
  _text_51:any;
  _el_52:any;
  _text_53:any;
  _el_54:any;
  _el_55:any;
  _text_56:any;
  _el_57:any;
  _text_58:any;
  _el_59:any;
  _text_60:any;
  _el_61:any;
  _text_62:any;
  _el_63:any;
  _text_64:any;
  _text_65:any;
  _el_66:any;
  _text_67:any;
  _el_68:any;
  _text_69:any;
  _text_70:any;
  _el_71:any;
  _el_72:any;
  _text_73:any;
  _el_74:any;
  _el_75:any;
  _text_76:any;
  _el_77:any;
  _el_78:any;
  _text_79:any;
  _el_80:any;
  _text_81:any;
  _el_82:any;
  _text_83:any;
  _el_84:any;
  _text_85:any;
  _text_86:any;
  _el_87:any;
  _text_88:any;
  _el_89:any;
  _text_90:any;
  _text_91:any;
  _el_92:any;
  _text_93:any;
  _el_94:any;
  _el_95:any;
  _text_96:any;
  _el_97:any;
  _text_98:any;
  _el_99:any;
  _text_100:any;
  _el_101:any;
  _text_102:any;
  _el_103:any;
  _text_104:any;
  _text_105:any;
  _el_106:any;
  _text_107:any;
  _el_108:any;
  _text_109:any;
  _text_110:any;
  _el_111:any;
  _text_112:any;
  _el_113:any;
  _text_114:any;
  _el_115:any;
  _text_116:any;
  _el_117:any;
  _text_118:any;
  _el_119:any;
  _text_120:any;
  _el_121:any;
  _text_122:any;
  _text_123:any;
  _el_124:any;
  _text_125:any;
  _el_126:any;
  _text_127:any;
  _text_128:any;
  _el_129:any;
  _text_130:any;
  _el_131:any;
  _text_132:any;
  _el_133:any;
  _text_134:any;
  _el_135:any;
  _text_136:any;
  _el_137:any;
  _text_138:any;
  _el_139:any;
  _text_140:any;
  _text_141:any;
  _el_142:any;
  _text_143:any;
  _el_144:any;
  _text_145:any;
  _text_146:any;
  _el_147:any;
  _text_148:any;
  _el_149:any;
  _text_150:any;
  _el_151:any;
  _text_152:any;
  _el_153:any;
  _text_154:any;
  _el_155:any;
  _text_156:any;
  _el_157:any;
  _text_158:any;
  _text_159:any;
  _el_160:any;
  _text_161:any;
  _el_162:any;
  _text_163:any;
  _text_164:any;
  _el_165:any;
  _text_166:any;
  _el_167:any;
  _text_168:any;
  _el_169:any;
  _text_170:any;
  _el_171:any;
  _text_172:any;
  _el_173:any;
  _text_174:any;
  _el_175:any;
  _text_176:any;
  _text_177:any;
  _text_178:any;
  _text_179:any;
  _el_180:any;
  _text_181:any;
  _text_182:any;
  _el_183:any;
  _text_184:any;
  _el_185:any;
  _text_186:any;
  _el_187:any;
  _text_188:any;
  _el_189:any;
  _text_190:any;
  _el_191:any;
  _text_192:any;
  _text_193:any;
  _el_194:any;
  _text_195:any;
  _text_196:any;
  _el_197:any;
  _text_198:any;
  _text_199:any;
  _el_200:any;
  _text_201:any;
  _text_202:any;
  _el_203:any;
  _text_204:any;
  _text_205:any;
  _el_206:any;
  _text_207:any;
  _text_208:any;
  _text_209:any;
  _el_210:any;
  _text_211:any;
  _el_212:any;
  _text_213:any;
  _text_214:any;
  _el_215:any;
  _text_216:any;
  _el_217:any;
  _text_218:any;
  _el_219:any;
  _text_220:any;
  _el_221:any;
  _text_222:any;
  _el_223:any;
  _text_224:any;
  _el_225:any;
  _text_226:any;
  _text_227:any;
  _el_228:any;
  _text_229:any;
  _el_230:any;
  _text_231:any;
  _text_232:any;
  _el_233:any;
  _text_234:any;
  _el_235:any;
  _text_236:any;
  _el_237:any;
  _text_238:any;
  _el_239:any;
  _text_240:any;
  _el_241:any;
  _el_242:any;
  _text_243:any;
  _el_244:any;
  _el_245:any;
  _text_246:any;
  _text_247:any;
  _el_248:any;
  _text_249:any;
  _el_250:any;
  _text_251:any;
  _text_252:any;
  _el_253:any;
  _text_254:any;
  _el_255:any;
  _text_256:any;
  _el_257:any;
  _text_258:any;
  _el_259:any;
  _el_260:any;
  _text_261:any;
  _el_262:any;
  _el_263:any;
  _text_264:any;
  _el_265:any;
  _el_266:any;
  _text_267:any;
  _text_268:any;
  _el_269:any;
  _text_270:any;
  _el_271:any;
  _text_272:any;
  _text_273:any;
  _el_274:any;
  _text_275:any;
  _el_276:any;
  _text_277:any;
  _el_278:any;
  _text_279:any;
  _el_280:any;
  _el_281:any;
  _text_282:any;
  _el_283:any;
  _el_284:any;
  _text_285:any;
  _el_286:any;
  _el_287:any;
  _text_288:any;
  _text_289:any;
  _el_290:any;
  _text_291:any;
  _el_292:any;
  _text_293:any;
  _text_294:any;
  _el_295:any;
  _text_296:any;
  _el_297:any;
  _el_298:any;
  _text_299:any;
  _el_300:any;
  _el_301:any;
  _text_302:any;
  _el_303:any;
  _text_304:any;
  _el_305:any;
  _el_306:any;
  _text_307:any;
  _el_308:any;
  _el_309:any;
  _text_310:any;
  _text_311:any;
  _el_312:any;
  _text_313:any;
  _el_314:any;
  _text_315:any;
  _text_316:any;
  _el_317:any;
  _el_318:any;
  _text_319:any;
  _el_320:any;
  _el_321:any;
  _text_322:any;
  _el_323:any;
  _el_324:any;
  _text_325:any;
  _el_326:any;
  _el_327:any;
  _text_328:any;
  _el_329:any;
  _el_330:any;
  _text_331:any;
  _el_332:any;
  _el_333:any;
  _text_334:any;
  _text_335:any;
  _el_336:any;
  _text_337:any;
  _el_338:any;
  _text_339:any;
  _text_340:any;
  _el_341:any;
  _el_342:any;
  _text_343:any;
  _el_344:any;
  _el_345:any;
  _text_346:any;
  _el_347:any;
  _el_348:any;
  _text_349:any;
  _el_350:any;
  _el_351:any;
  _text_352:any;
  _el_353:any;
  _el_354:any;
  _text_355:any;
  _el_356:any;
  _el_357:any;
  _text_358:any;
  _text_359:any;
  _text_360:any;
  _text_361:any;
  _text_362:any;
  _el_363:any;
  _text_364:any;
  _text_365:any;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement) {
    super(_View_CollisionTableComponent0,renderType_CollisionTableComponent,import6.ViewType.COMPONENT,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import2.AppElement {
    const parentRenderNode:any = this.renderer.createViewRoot(this.declarationAppElement.nativeElement);
    this._el_0 = this.renderer.createElement(parentRenderNode,'div',(null as any));
    this.renderer.setElementAttribute(this._el_0,'class','container');
    this._text_1 = this.renderer.createText(this._el_0,'\n    ',(null as any));
    this._el_2 = this.renderer.createElement(this._el_0,'div',(null as any));
    this.renderer.setElementAttribute(this._el_2,'class','row');
    this._text_3 = this.renderer.createText(this._el_2,'\n        ',(null as any));
    this._el_4 = this.renderer.createElement(this._el_2,'div',(null as any));
    this.renderer.setElementAttribute(this._el_4,'class','col-lg-1');
    this._text_5 = this.renderer.createText(this._el_2,'\n        ',(null as any));
    this._el_6 = this.renderer.createElement(this._el_2,'div',(null as any));
    this.renderer.setElementAttribute(this._el_6,'class','col-lg-10');
    this._text_7 = this.renderer.createText(this._el_6,'\n            ',(null as any));
    this._el_8 = this.renderer.createElement(this._el_6,'div',(null as any));
    this.renderer.setElementAttribute(this._el_8,'class','jumbotron');
    this._text_9 = this.renderer.createText(this._el_8,'\n                ',(null as any));
    this._el_10 = this.renderer.createElement(this._el_8,'h1',(null as any));
    this._text_11 = this.renderer.createText(this._el_10,'Unity Collision Table',(null as any));
    this._text_12 = this.renderer.createText(this._el_8,'\n                ',(null as any));
    this._el_13 = this.renderer.createElement(this._el_8,'p',(null as any));
    this._text_14 = this.renderer.createText(this._el_13,'Collision/Trigger detection between Rigidbody/Collider components.',(null as any));
    this._text_15 = this.renderer.createText(this._el_8,'\n            ',(null as any));
    this._text_16 = this.renderer.createText(this._el_6,'\n            ',(null as any));
    this._el_17 = this.renderer.createElement(this._el_6,'h2',(null as any));
    this._text_18 = this.renderer.createText(this._el_17,'OnCollision',(null as any));
    this._text_19 = this.renderer.createText(this._el_6,'\n            ',(null as any));
    this._el_20 = this.renderer.createElement(this._el_6,'table',(null as any));
    this.renderer.setElementAttribute(this._el_20,'class','table table-hover table-bordered');
    this._text_21 = this.renderer.createText(this._el_20,'\n            ',(null as any));
    this._el_22 = this.renderer.createElement(this._el_20,'tbody',(null as any));
    this._text_23 = this.renderer.createText(this._el_22,'	\n                ',(null as any));
    this._el_24 = this.renderer.createElement(this._el_22,'tr',(null as any));
    this._text_25 = this.renderer.createText(this._el_24,'\n                    ',(null as any));
    this._el_26 = this.renderer.createElement(this._el_24,'th',(null as any));
    this._text_27 = this.renderer.createText(this._el_24,'\n                    ',(null as any));
    this._el_28 = this.renderer.createElement(this._el_24,'th',(null as any));
    this._text_29 = this.renderer.createText(this._el_28,'Collider',(null as any));
    this._text_30 = this.renderer.createText(this._el_24,'\n                    ',(null as any));
    this._el_31 = this.renderer.createElement(this._el_24,'th',(null as any));
    this._text_32 = this.renderer.createText(this._el_31,'Rigidbody Collider',(null as any));
    this._text_33 = this.renderer.createText(this._el_24,'\n                    ',(null as any));
    this._el_34 = this.renderer.createElement(this._el_24,'th',(null as any));
    this._text_35 = this.renderer.createText(this._el_34,'Kinematic Rigidbody Collider',(null as any));
    this._text_36 = this.renderer.createText(this._el_24,'\n                    ',(null as any));
    this._el_37 = this.renderer.createElement(this._el_24,'th',(null as any));
    this._text_38 = this.renderer.createText(this._el_37,'Trigger Collider',(null as any));
    this._text_39 = this.renderer.createText(this._el_24,'\n                    ',(null as any));
    this._el_40 = this.renderer.createElement(this._el_24,'th',(null as any));
    this._text_41 = this.renderer.createText(this._el_40,'Rigidbody Trigger Collider',(null as any));
    this._text_42 = this.renderer.createText(this._el_24,'\n                    ',(null as any));
    this._el_43 = this.renderer.createElement(this._el_24,'th',(null as any));
    this._text_44 = this.renderer.createText(this._el_43,'Kinematic Rigidbody Trigger Collider',(null as any));
    this._text_45 = this.renderer.createText(this._el_24,'\n                ',(null as any));
    this._text_46 = this.renderer.createText(this._el_22,'\n                ',(null as any));
    this._el_47 = this.renderer.createElement(this._el_22,'tr',(null as any));
    this._text_48 = this.renderer.createText(this._el_47,'\n                    ',(null as any));
    this._el_49 = this.renderer.createElement(this._el_47,'th',(null as any));
    this._text_50 = this.renderer.createText(this._el_49,'Collider',(null as any));
    this._text_51 = this.renderer.createText(this._el_47,'\n                    ',(null as any));
    this._el_52 = this.renderer.createElement(this._el_47,'td',(null as any));
    this._text_53 = this.renderer.createText(this._el_47,'\n                    ',(null as any));
    this._el_54 = this.renderer.createElement(this._el_47,'td',(null as any));
    this._el_55 = this.renderer.createElement(this._el_54,'span',(null as any));
    this.renderer.setElementAttribute(this._el_55,'aria-hidden','true');
    this.renderer.setElementAttribute(this._el_55,'class','glyphicon glyphicon-ok');
    this._text_56 = this.renderer.createText(this._el_47,'\n                    ',(null as any));
    this._el_57 = this.renderer.createElement(this._el_47,'td',(null as any));
    this._text_58 = this.renderer.createText(this._el_47,'\n                    ',(null as any));
    this._el_59 = this.renderer.createElement(this._el_47,'td',(null as any));
    this._text_60 = this.renderer.createText(this._el_47,'\n                    ',(null as any));
    this._el_61 = this.renderer.createElement(this._el_47,'td',(null as any));
    this._text_62 = this.renderer.createText(this._el_47,'\n                    ',(null as any));
    this._el_63 = this.renderer.createElement(this._el_47,'td',(null as any));
    this._text_64 = this.renderer.createText(this._el_47,'\n                ',(null as any));
    this._text_65 = this.renderer.createText(this._el_22,'\n                ',(null as any));
    this._el_66 = this.renderer.createElement(this._el_22,'tr',(null as any));
    this._text_67 = this.renderer.createText(this._el_66,'\n                    ',(null as any));
    this._el_68 = this.renderer.createElement(this._el_66,'th',(null as any));
    this._text_69 = this.renderer.createText(this._el_68,'Rigidbody Collider',(null as any));
    this._text_70 = this.renderer.createText(this._el_66,'\n                    ',(null as any));
    this._el_71 = this.renderer.createElement(this._el_66,'td',(null as any));
    this._el_72 = this.renderer.createElement(this._el_71,'span',(null as any));
    this.renderer.setElementAttribute(this._el_72,'aria-hidden','true');
    this.renderer.setElementAttribute(this._el_72,'class','glyphicon glyphicon-ok');
    this._text_73 = this.renderer.createText(this._el_66,'\n                    ',(null as any));
    this._el_74 = this.renderer.createElement(this._el_66,'td',(null as any));
    this._el_75 = this.renderer.createElement(this._el_74,'span',(null as any));
    this.renderer.setElementAttribute(this._el_75,'aria-hidden','true');
    this.renderer.setElementAttribute(this._el_75,'class','glyphicon glyphicon-ok');
    this._text_76 = this.renderer.createText(this._el_66,'\n                    ',(null as any));
    this._el_77 = this.renderer.createElement(this._el_66,'td',(null as any));
    this._el_78 = this.renderer.createElement(this._el_77,'span',(null as any));
    this.renderer.setElementAttribute(this._el_78,'aria-hidden','true');
    this.renderer.setElementAttribute(this._el_78,'class','glyphicon glyphicon-ok');
    this._text_79 = this.renderer.createText(this._el_66,'\n                    ',(null as any));
    this._el_80 = this.renderer.createElement(this._el_66,'td',(null as any));
    this._text_81 = this.renderer.createText(this._el_66,'\n                    ',(null as any));
    this._el_82 = this.renderer.createElement(this._el_66,'td',(null as any));
    this._text_83 = this.renderer.createText(this._el_66,'\n                    ',(null as any));
    this._el_84 = this.renderer.createElement(this._el_66,'td',(null as any));
    this._text_85 = this.renderer.createText(this._el_66,'\n                ',(null as any));
    this._text_86 = this.renderer.createText(this._el_22,'\n                ',(null as any));
    this._el_87 = this.renderer.createElement(this._el_22,'tr',(null as any));
    this._text_88 = this.renderer.createText(this._el_87,'\n                    ',(null as any));
    this._el_89 = this.renderer.createElement(this._el_87,'th',(null as any));
    this._text_90 = this.renderer.createText(this._el_89,'Kinematic Rigidbody Collider',(null as any));
    this._text_91 = this.renderer.createText(this._el_87,'\n                    ',(null as any));
    this._el_92 = this.renderer.createElement(this._el_87,'td',(null as any));
    this._text_93 = this.renderer.createText(this._el_87,'\n                    ',(null as any));
    this._el_94 = this.renderer.createElement(this._el_87,'td',(null as any));
    this._el_95 = this.renderer.createElement(this._el_94,'span',(null as any));
    this.renderer.setElementAttribute(this._el_95,'aria-hidden','true');
    this.renderer.setElementAttribute(this._el_95,'class','glyphicon glyphicon-ok');
    this._text_96 = this.renderer.createText(this._el_87,'\n                    ',(null as any));
    this._el_97 = this.renderer.createElement(this._el_87,'td',(null as any));
    this._text_98 = this.renderer.createText(this._el_87,'\n                    ',(null as any));
    this._el_99 = this.renderer.createElement(this._el_87,'td',(null as any));
    this._text_100 = this.renderer.createText(this._el_87,'\n                    ',(null as any));
    this._el_101 = this.renderer.createElement(this._el_87,'td',(null as any));
    this._text_102 = this.renderer.createText(this._el_87,'\n                    ',(null as any));
    this._el_103 = this.renderer.createElement(this._el_87,'td',(null as any));
    this._text_104 = this.renderer.createText(this._el_87,'\n                ',(null as any));
    this._text_105 = this.renderer.createText(this._el_22,'\n                ',(null as any));
    this._el_106 = this.renderer.createElement(this._el_22,'tr',(null as any));
    this._text_107 = this.renderer.createText(this._el_106,'\n                    ',(null as any));
    this._el_108 = this.renderer.createElement(this._el_106,'th',(null as any));
    this._text_109 = this.renderer.createText(this._el_108,'Kinematic Rigidbody Collider',(null as any));
    this._text_110 = this.renderer.createText(this._el_106,'\n                    ',(null as any));
    this._el_111 = this.renderer.createElement(this._el_106,'td',(null as any));
    this._text_112 = this.renderer.createText(this._el_106,'\n                    ',(null as any));
    this._el_113 = this.renderer.createElement(this._el_106,'td',(null as any));
    this._text_114 = this.renderer.createText(this._el_106,'\n                    ',(null as any));
    this._el_115 = this.renderer.createElement(this._el_106,'td',(null as any));
    this._text_116 = this.renderer.createText(this._el_106,'\n                    ',(null as any));
    this._el_117 = this.renderer.createElement(this._el_106,'td',(null as any));
    this._text_118 = this.renderer.createText(this._el_106,'\n                    ',(null as any));
    this._el_119 = this.renderer.createElement(this._el_106,'td',(null as any));
    this._text_120 = this.renderer.createText(this._el_106,'\n                    ',(null as any));
    this._el_121 = this.renderer.createElement(this._el_106,'td',(null as any));
    this._text_122 = this.renderer.createText(this._el_106,'\n                ',(null as any));
    this._text_123 = this.renderer.createText(this._el_22,'\n                ',(null as any));
    this._el_124 = this.renderer.createElement(this._el_22,'tr',(null as any));
    this._text_125 = this.renderer.createText(this._el_124,'\n                    ',(null as any));
    this._el_126 = this.renderer.createElement(this._el_124,'th',(null as any));
    this._text_127 = this.renderer.createText(this._el_126,'Trigger Collider',(null as any));
    this._text_128 = this.renderer.createText(this._el_124,'\n                    ',(null as any));
    this._el_129 = this.renderer.createElement(this._el_124,'td',(null as any));
    this._text_130 = this.renderer.createText(this._el_124,'\n                    ',(null as any));
    this._el_131 = this.renderer.createElement(this._el_124,'td',(null as any));
    this._text_132 = this.renderer.createText(this._el_124,'\n                    ',(null as any));
    this._el_133 = this.renderer.createElement(this._el_124,'td',(null as any));
    this._text_134 = this.renderer.createText(this._el_124,'\n                    ',(null as any));
    this._el_135 = this.renderer.createElement(this._el_124,'td',(null as any));
    this._text_136 = this.renderer.createText(this._el_124,'\n                    ',(null as any));
    this._el_137 = this.renderer.createElement(this._el_124,'td',(null as any));
    this._text_138 = this.renderer.createText(this._el_124,'\n                    ',(null as any));
    this._el_139 = this.renderer.createElement(this._el_124,'td',(null as any));
    this._text_140 = this.renderer.createText(this._el_124,'\n                ',(null as any));
    this._text_141 = this.renderer.createText(this._el_22,'\n                ',(null as any));
    this._el_142 = this.renderer.createElement(this._el_22,'tr',(null as any));
    this._text_143 = this.renderer.createText(this._el_142,'\n                    ',(null as any));
    this._el_144 = this.renderer.createElement(this._el_142,'th',(null as any));
    this._text_145 = this.renderer.createText(this._el_144,'Rigidbody Trigger Collider',(null as any));
    this._text_146 = this.renderer.createText(this._el_142,'\n                    ',(null as any));
    this._el_147 = this.renderer.createElement(this._el_142,'td',(null as any));
    this._text_148 = this.renderer.createText(this._el_142,'\n                    ',(null as any));
    this._el_149 = this.renderer.createElement(this._el_142,'td',(null as any));
    this._text_150 = this.renderer.createText(this._el_142,'\n                    ',(null as any));
    this._el_151 = this.renderer.createElement(this._el_142,'td',(null as any));
    this._text_152 = this.renderer.createText(this._el_142,'\n                    ',(null as any));
    this._el_153 = this.renderer.createElement(this._el_142,'td',(null as any));
    this._text_154 = this.renderer.createText(this._el_142,'\n                    ',(null as any));
    this._el_155 = this.renderer.createElement(this._el_142,'td',(null as any));
    this._text_156 = this.renderer.createText(this._el_142,'\n                    ',(null as any));
    this._el_157 = this.renderer.createElement(this._el_142,'td',(null as any));
    this._text_158 = this.renderer.createText(this._el_142,'\n                ',(null as any));
    this._text_159 = this.renderer.createText(this._el_22,'\n                ',(null as any));
    this._el_160 = this.renderer.createElement(this._el_22,'tr',(null as any));
    this._text_161 = this.renderer.createText(this._el_160,'\n                    ',(null as any));
    this._el_162 = this.renderer.createElement(this._el_160,'th',(null as any));
    this._text_163 = this.renderer.createText(this._el_162,'Kinematic Rigidbody Trigger Collider',(null as any));
    this._text_164 = this.renderer.createText(this._el_160,'\n                    ',(null as any));
    this._el_165 = this.renderer.createElement(this._el_160,'td',(null as any));
    this._text_166 = this.renderer.createText(this._el_160,'\n                    ',(null as any));
    this._el_167 = this.renderer.createElement(this._el_160,'td',(null as any));
    this._text_168 = this.renderer.createText(this._el_160,'\n                    ',(null as any));
    this._el_169 = this.renderer.createElement(this._el_160,'td',(null as any));
    this._text_170 = this.renderer.createText(this._el_160,'\n                    ',(null as any));
    this._el_171 = this.renderer.createElement(this._el_160,'td',(null as any));
    this._text_172 = this.renderer.createText(this._el_160,'\n                    ',(null as any));
    this._el_173 = this.renderer.createElement(this._el_160,'td',(null as any));
    this._text_174 = this.renderer.createText(this._el_160,'\n                    ',(null as any));
    this._el_175 = this.renderer.createElement(this._el_160,'td',(null as any));
    this._text_176 = this.renderer.createText(this._el_160,'\n                ',(null as any));
    this._text_177 = this.renderer.createText(this._el_22,'\n            ',(null as any));
    this._text_178 = this.renderer.createText(this._el_20,'\n        ',(null as any));
    this._text_179 = this.renderer.createText(this._el_6,'\n            ',(null as any));
    this._el_180 = this.renderer.createElement(this._el_6,'h2',(null as any));
    this._text_181 = this.renderer.createText(this._el_180,'OnTrigger',(null as any));
    this._text_182 = this.renderer.createText(this._el_6,'\n            ',(null as any));
    this._el_183 = this.renderer.createElement(this._el_6,'table',(null as any));
    this.renderer.setElementAttribute(this._el_183,'class','table table-hover table-bordered');
    this._text_184 = this.renderer.createText(this._el_183,'\n            ',(null as any));
    this._el_185 = this.renderer.createElement(this._el_183,'tbody',(null as any));
    this._text_186 = this.renderer.createText(this._el_185,'	\n                ',(null as any));
    this._el_187 = this.renderer.createElement(this._el_185,'tr',(null as any));
    this._text_188 = this.renderer.createText(this._el_187,'\n                    ',(null as any));
    this._el_189 = this.renderer.createElement(this._el_187,'th',(null as any));
    this._text_190 = this.renderer.createText(this._el_187,'\n                    ',(null as any));
    this._el_191 = this.renderer.createElement(this._el_187,'th',(null as any));
    this._text_192 = this.renderer.createText(this._el_191,'Collider',(null as any));
    this._text_193 = this.renderer.createText(this._el_187,'\n                    ',(null as any));
    this._el_194 = this.renderer.createElement(this._el_187,'th',(null as any));
    this._text_195 = this.renderer.createText(this._el_194,'Rigidbody Collider',(null as any));
    this._text_196 = this.renderer.createText(this._el_187,'\n                    ',(null as any));
    this._el_197 = this.renderer.createElement(this._el_187,'th',(null as any));
    this._text_198 = this.renderer.createText(this._el_197,'Kinematic Rigidbody Collider',(null as any));
    this._text_199 = this.renderer.createText(this._el_187,'\n                    ',(null as any));
    this._el_200 = this.renderer.createElement(this._el_187,'th',(null as any));
    this._text_201 = this.renderer.createText(this._el_200,'Trigger Collider',(null as any));
    this._text_202 = this.renderer.createText(this._el_187,'\n                    ',(null as any));
    this._el_203 = this.renderer.createElement(this._el_187,'th',(null as any));
    this._text_204 = this.renderer.createText(this._el_203,'Rigidbody Trigger Collider',(null as any));
    this._text_205 = this.renderer.createText(this._el_187,'\n                    ',(null as any));
    this._el_206 = this.renderer.createElement(this._el_187,'th',(null as any));
    this._text_207 = this.renderer.createText(this._el_206,'Kinematic Rigidbody Trigger Collider',(null as any));
    this._text_208 = this.renderer.createText(this._el_187,'\n                ',(null as any));
    this._text_209 = this.renderer.createText(this._el_185,'\n                ',(null as any));
    this._el_210 = this.renderer.createElement(this._el_185,'tr',(null as any));
    this._text_211 = this.renderer.createText(this._el_210,'\n                    ',(null as any));
    this._el_212 = this.renderer.createElement(this._el_210,'th',(null as any));
    this._text_213 = this.renderer.createText(this._el_212,'Collider',(null as any));
    this._text_214 = this.renderer.createText(this._el_210,'\n                    ',(null as any));
    this._el_215 = this.renderer.createElement(this._el_210,'td',(null as any));
    this._text_216 = this.renderer.createText(this._el_210,'\n                    ',(null as any));
    this._el_217 = this.renderer.createElement(this._el_210,'td',(null as any));
    this._text_218 = this.renderer.createText(this._el_210,'\n                    ',(null as any));
    this._el_219 = this.renderer.createElement(this._el_210,'td',(null as any));
    this._text_220 = this.renderer.createText(this._el_210,'\n                    ',(null as any));
    this._el_221 = this.renderer.createElement(this._el_210,'td',(null as any));
    this._text_222 = this.renderer.createText(this._el_210,'\n                    ',(null as any));
    this._el_223 = this.renderer.createElement(this._el_210,'td',(null as any));
    this._text_224 = this.renderer.createText(this._el_210,'\n                    ',(null as any));
    this._el_225 = this.renderer.createElement(this._el_210,'td',(null as any));
    this._text_226 = this.renderer.createText(this._el_210,'\n                ',(null as any));
    this._text_227 = this.renderer.createText(this._el_185,'\n                ',(null as any));
    this._el_228 = this.renderer.createElement(this._el_185,'tr',(null as any));
    this._text_229 = this.renderer.createText(this._el_228,'\n                    ',(null as any));
    this._el_230 = this.renderer.createElement(this._el_228,'th',(null as any));
    this._text_231 = this.renderer.createText(this._el_230,'Rigidbody Collider',(null as any));
    this._text_232 = this.renderer.createText(this._el_228,'\n                    ',(null as any));
    this._el_233 = this.renderer.createElement(this._el_228,'td',(null as any));
    this._text_234 = this.renderer.createText(this._el_228,'\n                    ',(null as any));
    this._el_235 = this.renderer.createElement(this._el_228,'td',(null as any));
    this._text_236 = this.renderer.createText(this._el_228,'\n                    ',(null as any));
    this._el_237 = this.renderer.createElement(this._el_228,'td',(null as any));
    this._text_238 = this.renderer.createText(this._el_228,'\n                    ',(null as any));
    this._el_239 = this.renderer.createElement(this._el_228,'td',(null as any));
    this._text_240 = this.renderer.createText(this._el_228,'\n                    ',(null as any));
    this._el_241 = this.renderer.createElement(this._el_228,'td',(null as any));
    this._el_242 = this.renderer.createElement(this._el_241,'span',(null as any));
    this.renderer.setElementAttribute(this._el_242,'aria-hidden','true');
    this.renderer.setElementAttribute(this._el_242,'class','glyphicon glyphicon-ok');
    this._text_243 = this.renderer.createText(this._el_228,'\n                    ',(null as any));
    this._el_244 = this.renderer.createElement(this._el_228,'td',(null as any));
    this._el_245 = this.renderer.createElement(this._el_244,'span',(null as any));
    this.renderer.setElementAttribute(this._el_245,'aria-hidden','true');
    this.renderer.setElementAttribute(this._el_245,'class','glyphicon glyphicon-ok');
    this._text_246 = this.renderer.createText(this._el_228,'\n                ',(null as any));
    this._text_247 = this.renderer.createText(this._el_185,'\n                ',(null as any));
    this._el_248 = this.renderer.createElement(this._el_185,'tr',(null as any));
    this._text_249 = this.renderer.createText(this._el_248,'\n                    ',(null as any));
    this._el_250 = this.renderer.createElement(this._el_248,'th',(null as any));
    this._text_251 = this.renderer.createText(this._el_250,'Kinematic Rigidbody Collider',(null as any));
    this._text_252 = this.renderer.createText(this._el_248,'\n                    ',(null as any));
    this._el_253 = this.renderer.createElement(this._el_248,'td',(null as any));
    this._text_254 = this.renderer.createText(this._el_248,'\n                    ',(null as any));
    this._el_255 = this.renderer.createElement(this._el_248,'td',(null as any));
    this._text_256 = this.renderer.createText(this._el_248,'\n                    ',(null as any));
    this._el_257 = this.renderer.createElement(this._el_248,'td',(null as any));
    this._text_258 = this.renderer.createText(this._el_248,'\n                    ',(null as any));
    this._el_259 = this.renderer.createElement(this._el_248,'td',(null as any));
    this._el_260 = this.renderer.createElement(this._el_259,'span',(null as any));
    this.renderer.setElementAttribute(this._el_260,'aria-hidden','true');
    this.renderer.setElementAttribute(this._el_260,'class','glyphicon glyphicon-ok');
    this._text_261 = this.renderer.createText(this._el_248,'\n                    ',(null as any));
    this._el_262 = this.renderer.createElement(this._el_248,'td',(null as any));
    this._el_263 = this.renderer.createElement(this._el_262,'span',(null as any));
    this.renderer.setElementAttribute(this._el_263,'aria-hidden','true');
    this.renderer.setElementAttribute(this._el_263,'class','glyphicon glyphicon-ok');
    this._text_264 = this.renderer.createText(this._el_248,'\n                    ',(null as any));
    this._el_265 = this.renderer.createElement(this._el_248,'td',(null as any));
    this._el_266 = this.renderer.createElement(this._el_265,'span',(null as any));
    this.renderer.setElementAttribute(this._el_266,'aria-hidden','true');
    this.renderer.setElementAttribute(this._el_266,'class','glyphicon glyphicon-ok');
    this._text_267 = this.renderer.createText(this._el_248,'\n                ',(null as any));
    this._text_268 = this.renderer.createText(this._el_185,'\n                ',(null as any));
    this._el_269 = this.renderer.createElement(this._el_185,'tr',(null as any));
    this._text_270 = this.renderer.createText(this._el_269,'\n                    ',(null as any));
    this._el_271 = this.renderer.createElement(this._el_269,'th',(null as any));
    this._text_272 = this.renderer.createText(this._el_271,'Kinematic Rigidbody Collider',(null as any));
    this._text_273 = this.renderer.createText(this._el_269,'\n                    ',(null as any));
    this._el_274 = this.renderer.createElement(this._el_269,'td',(null as any));
    this._text_275 = this.renderer.createText(this._el_269,'\n                    ',(null as any));
    this._el_276 = this.renderer.createElement(this._el_269,'td',(null as any));
    this._text_277 = this.renderer.createText(this._el_269,'\n                    ',(null as any));
    this._el_278 = this.renderer.createElement(this._el_269,'td',(null as any));
    this._text_279 = this.renderer.createText(this._el_269,'\n                    ',(null as any));
    this._el_280 = this.renderer.createElement(this._el_269,'td',(null as any));
    this._el_281 = this.renderer.createElement(this._el_280,'span',(null as any));
    this.renderer.setElementAttribute(this._el_281,'aria-hidden','true');
    this.renderer.setElementAttribute(this._el_281,'class','glyphicon glyphicon-ok');
    this._text_282 = this.renderer.createText(this._el_269,'\n                    ',(null as any));
    this._el_283 = this.renderer.createElement(this._el_269,'td',(null as any));
    this._el_284 = this.renderer.createElement(this._el_283,'span',(null as any));
    this.renderer.setElementAttribute(this._el_284,'aria-hidden','true');
    this.renderer.setElementAttribute(this._el_284,'class','glyphicon glyphicon-ok');
    this._text_285 = this.renderer.createText(this._el_269,'\n                    ',(null as any));
    this._el_286 = this.renderer.createElement(this._el_269,'td',(null as any));
    this._el_287 = this.renderer.createElement(this._el_286,'span',(null as any));
    this.renderer.setElementAttribute(this._el_287,'aria-hidden','true');
    this.renderer.setElementAttribute(this._el_287,'class','glyphicon glyphicon-ok');
    this._text_288 = this.renderer.createText(this._el_269,'\n                ',(null as any));
    this._text_289 = this.renderer.createText(this._el_185,'\n                ',(null as any));
    this._el_290 = this.renderer.createElement(this._el_185,'tr',(null as any));
    this._text_291 = this.renderer.createText(this._el_290,'\n                    ',(null as any));
    this._el_292 = this.renderer.createElement(this._el_290,'th',(null as any));
    this._text_293 = this.renderer.createText(this._el_292,'Trigger Collider',(null as any));
    this._text_294 = this.renderer.createText(this._el_290,'\n                    ',(null as any));
    this._el_295 = this.renderer.createElement(this._el_290,'td',(null as any));
    this._text_296 = this.renderer.createText(this._el_290,'\n                    ',(null as any));
    this._el_297 = this.renderer.createElement(this._el_290,'td',(null as any));
    this._el_298 = this.renderer.createElement(this._el_297,'span',(null as any));
    this.renderer.setElementAttribute(this._el_298,'aria-hidden','true');
    this.renderer.setElementAttribute(this._el_298,'class','glyphicon glyphicon-ok');
    this._text_299 = this.renderer.createText(this._el_290,'\n                    ',(null as any));
    this._el_300 = this.renderer.createElement(this._el_290,'td',(null as any));
    this._el_301 = this.renderer.createElement(this._el_300,'span',(null as any));
    this.renderer.setElementAttribute(this._el_301,'aria-hidden','true');
    this.renderer.setElementAttribute(this._el_301,'class','glyphicon glyphicon-ok');
    this._text_302 = this.renderer.createText(this._el_290,'\n                    ',(null as any));
    this._el_303 = this.renderer.createElement(this._el_290,'td',(null as any));
    this._text_304 = this.renderer.createText(this._el_290,'\n                    ',(null as any));
    this._el_305 = this.renderer.createElement(this._el_290,'td',(null as any));
    this._el_306 = this.renderer.createElement(this._el_305,'span',(null as any));
    this.renderer.setElementAttribute(this._el_306,'aria-hidden','true');
    this.renderer.setElementAttribute(this._el_306,'class','glyphicon glyphicon-ok');
    this._text_307 = this.renderer.createText(this._el_290,'\n                    ',(null as any));
    this._el_308 = this.renderer.createElement(this._el_290,'td',(null as any));
    this._el_309 = this.renderer.createElement(this._el_308,'span',(null as any));
    this.renderer.setElementAttribute(this._el_309,'aria-hidden','true');
    this.renderer.setElementAttribute(this._el_309,'class','glyphicon glyphicon-ok');
    this._text_310 = this.renderer.createText(this._el_290,'\n                ',(null as any));
    this._text_311 = this.renderer.createText(this._el_185,'\n                ',(null as any));
    this._el_312 = this.renderer.createElement(this._el_185,'tr',(null as any));
    this._text_313 = this.renderer.createText(this._el_312,'\n                    ',(null as any));
    this._el_314 = this.renderer.createElement(this._el_312,'th',(null as any));
    this._text_315 = this.renderer.createText(this._el_314,'Rigidbody Trigger Collider',(null as any));
    this._text_316 = this.renderer.createText(this._el_312,'\n                    ',(null as any));
    this._el_317 = this.renderer.createElement(this._el_312,'td',(null as any));
    this._el_318 = this.renderer.createElement(this._el_317,'span',(null as any));
    this.renderer.setElementAttribute(this._el_318,'aria-hidden','true');
    this.renderer.setElementAttribute(this._el_318,'class','glyphicon glyphicon-ok');
    this._text_319 = this.renderer.createText(this._el_312,'\n                    ',(null as any));
    this._el_320 = this.renderer.createElement(this._el_312,'td',(null as any));
    this._el_321 = this.renderer.createElement(this._el_320,'span',(null as any));
    this.renderer.setElementAttribute(this._el_321,'aria-hidden','true');
    this.renderer.setElementAttribute(this._el_321,'class','glyphicon glyphicon-ok');
    this._text_322 = this.renderer.createText(this._el_312,'\n                    ',(null as any));
    this._el_323 = this.renderer.createElement(this._el_312,'td',(null as any));
    this._el_324 = this.renderer.createElement(this._el_323,'span',(null as any));
    this.renderer.setElementAttribute(this._el_324,'aria-hidden','true');
    this.renderer.setElementAttribute(this._el_324,'class','glyphicon glyphicon-ok');
    this._text_325 = this.renderer.createText(this._el_312,'\n                    ',(null as any));
    this._el_326 = this.renderer.createElement(this._el_312,'td',(null as any));
    this._el_327 = this.renderer.createElement(this._el_326,'span',(null as any));
    this.renderer.setElementAttribute(this._el_327,'aria-hidden','true');
    this.renderer.setElementAttribute(this._el_327,'class','glyphicon glyphicon-ok');
    this._text_328 = this.renderer.createText(this._el_312,'\n                    ',(null as any));
    this._el_329 = this.renderer.createElement(this._el_312,'td',(null as any));
    this._el_330 = this.renderer.createElement(this._el_329,'span',(null as any));
    this.renderer.setElementAttribute(this._el_330,'aria-hidden','true');
    this.renderer.setElementAttribute(this._el_330,'class','glyphicon glyphicon-ok');
    this._text_331 = this.renderer.createText(this._el_312,'\n                    ',(null as any));
    this._el_332 = this.renderer.createElement(this._el_312,'td',(null as any));
    this._el_333 = this.renderer.createElement(this._el_332,'span',(null as any));
    this.renderer.setElementAttribute(this._el_333,'aria-hidden','true');
    this.renderer.setElementAttribute(this._el_333,'class','glyphicon glyphicon-ok');
    this._text_334 = this.renderer.createText(this._el_312,'\n                ',(null as any));
    this._text_335 = this.renderer.createText(this._el_185,'\n                ',(null as any));
    this._el_336 = this.renderer.createElement(this._el_185,'tr',(null as any));
    this._text_337 = this.renderer.createText(this._el_336,'\n                    ',(null as any));
    this._el_338 = this.renderer.createElement(this._el_336,'th',(null as any));
    this._text_339 = this.renderer.createText(this._el_338,'Kinematic Rigidbody Trigger Collider',(null as any));
    this._text_340 = this.renderer.createText(this._el_336,'\n                    ',(null as any));
    this._el_341 = this.renderer.createElement(this._el_336,'td',(null as any));
    this._el_342 = this.renderer.createElement(this._el_341,'span',(null as any));
    this.renderer.setElementAttribute(this._el_342,'aria-hidden','true');
    this.renderer.setElementAttribute(this._el_342,'class','glyphicon glyphicon-ok');
    this._text_343 = this.renderer.createText(this._el_336,'\n                    ',(null as any));
    this._el_344 = this.renderer.createElement(this._el_336,'td',(null as any));
    this._el_345 = this.renderer.createElement(this._el_344,'span',(null as any));
    this.renderer.setElementAttribute(this._el_345,'aria-hidden','true');
    this.renderer.setElementAttribute(this._el_345,'class','glyphicon glyphicon-ok');
    this._text_346 = this.renderer.createText(this._el_336,'\n                    ',(null as any));
    this._el_347 = this.renderer.createElement(this._el_336,'td',(null as any));
    this._el_348 = this.renderer.createElement(this._el_347,'span',(null as any));
    this.renderer.setElementAttribute(this._el_348,'aria-hidden','true');
    this.renderer.setElementAttribute(this._el_348,'class','glyphicon glyphicon-ok');
    this._text_349 = this.renderer.createText(this._el_336,'\n                    ',(null as any));
    this._el_350 = this.renderer.createElement(this._el_336,'td',(null as any));
    this._el_351 = this.renderer.createElement(this._el_350,'span',(null as any));
    this.renderer.setElementAttribute(this._el_351,'aria-hidden','true');
    this.renderer.setElementAttribute(this._el_351,'class','glyphicon glyphicon-ok');
    this._text_352 = this.renderer.createText(this._el_336,'\n                    ',(null as any));
    this._el_353 = this.renderer.createElement(this._el_336,'td',(null as any));
    this._el_354 = this.renderer.createElement(this._el_353,'span',(null as any));
    this.renderer.setElementAttribute(this._el_354,'aria-hidden','true');
    this.renderer.setElementAttribute(this._el_354,'class','glyphicon glyphicon-ok');
    this._text_355 = this.renderer.createText(this._el_336,'\n                    ',(null as any));
    this._el_356 = this.renderer.createElement(this._el_336,'td',(null as any));
    this._el_357 = this.renderer.createElement(this._el_356,'span',(null as any));
    this.renderer.setElementAttribute(this._el_357,'aria-hidden','true');
    this.renderer.setElementAttribute(this._el_357,'class','glyphicon glyphicon-ok');
    this._text_358 = this.renderer.createText(this._el_336,'\n                ',(null as any));
    this._text_359 = this.renderer.createText(this._el_185,'\n            ',(null as any));
    this._text_360 = this.renderer.createText(this._el_183,'\n        ',(null as any));
    this._text_361 = this.renderer.createText(this._el_6,'\n        ',(null as any));
    this._text_362 = this.renderer.createText(this._el_2,'\n        ',(null as any));
    this._el_363 = this.renderer.createElement(this._el_2,'div',(null as any));
    this.renderer.setElementAttribute(this._el_363,'class','col-lg-1');
    this._text_364 = this.renderer.createText(this._el_2,'\n    ',(null as any));
    this._text_365 = this.renderer.createText(this._el_0,'\n',(null as any));
    this.init([],[
      this._el_0,
      this._text_1,
      this._el_2,
      this._text_3,
      this._el_4,
      this._text_5,
      this._el_6,
      this._text_7,
      this._el_8,
      this._text_9,
      this._el_10,
      this._text_11,
      this._text_12,
      this._el_13,
      this._text_14,
      this._text_15,
      this._text_16,
      this._el_17,
      this._text_18,
      this._text_19,
      this._el_20,
      this._text_21,
      this._el_22,
      this._text_23,
      this._el_24,
      this._text_25,
      this._el_26,
      this._text_27,
      this._el_28,
      this._text_29,
      this._text_30,
      this._el_31,
      this._text_32,
      this._text_33,
      this._el_34,
      this._text_35,
      this._text_36,
      this._el_37,
      this._text_38,
      this._text_39,
      this._el_40,
      this._text_41,
      this._text_42,
      this._el_43,
      this._text_44,
      this._text_45,
      this._text_46,
      this._el_47,
      this._text_48,
      this._el_49,
      this._text_50,
      this._text_51,
      this._el_52,
      this._text_53,
      this._el_54,
      this._el_55,
      this._text_56,
      this._el_57,
      this._text_58,
      this._el_59,
      this._text_60,
      this._el_61,
      this._text_62,
      this._el_63,
      this._text_64,
      this._text_65,
      this._el_66,
      this._text_67,
      this._el_68,
      this._text_69,
      this._text_70,
      this._el_71,
      this._el_72,
      this._text_73,
      this._el_74,
      this._el_75,
      this._text_76,
      this._el_77,
      this._el_78,
      this._text_79,
      this._el_80,
      this._text_81,
      this._el_82,
      this._text_83,
      this._el_84,
      this._text_85,
      this._text_86,
      this._el_87,
      this._text_88,
      this._el_89,
      this._text_90,
      this._text_91,
      this._el_92,
      this._text_93,
      this._el_94,
      this._el_95,
      this._text_96,
      this._el_97,
      this._text_98,
      this._el_99,
      this._text_100,
      this._el_101,
      this._text_102,
      this._el_103,
      this._text_104,
      this._text_105,
      this._el_106,
      this._text_107,
      this._el_108,
      this._text_109,
      this._text_110,
      this._el_111,
      this._text_112,
      this._el_113,
      this._text_114,
      this._el_115,
      this._text_116,
      this._el_117,
      this._text_118,
      this._el_119,
      this._text_120,
      this._el_121,
      this._text_122,
      this._text_123,
      this._el_124,
      this._text_125,
      this._el_126,
      this._text_127,
      this._text_128,
      this._el_129,
      this._text_130,
      this._el_131,
      this._text_132,
      this._el_133,
      this._text_134,
      this._el_135,
      this._text_136,
      this._el_137,
      this._text_138,
      this._el_139,
      this._text_140,
      this._text_141,
      this._el_142,
      this._text_143,
      this._el_144,
      this._text_145,
      this._text_146,
      this._el_147,
      this._text_148,
      this._el_149,
      this._text_150,
      this._el_151,
      this._text_152,
      this._el_153,
      this._text_154,
      this._el_155,
      this._text_156,
      this._el_157,
      this._text_158,
      this._text_159,
      this._el_160,
      this._text_161,
      this._el_162,
      this._text_163,
      this._text_164,
      this._el_165,
      this._text_166,
      this._el_167,
      this._text_168,
      this._el_169,
      this._text_170,
      this._el_171,
      this._text_172,
      this._el_173,
      this._text_174,
      this._el_175,
      this._text_176,
      this._text_177,
      this._text_178,
      this._text_179,
      this._el_180,
      this._text_181,
      this._text_182,
      this._el_183,
      this._text_184,
      this._el_185,
      this._text_186,
      this._el_187,
      this._text_188,
      this._el_189,
      this._text_190,
      this._el_191,
      this._text_192,
      this._text_193,
      this._el_194,
      this._text_195,
      this._text_196,
      this._el_197,
      this._text_198,
      this._text_199,
      this._el_200,
      this._text_201,
      this._text_202,
      this._el_203,
      this._text_204,
      this._text_205,
      this._el_206,
      this._text_207,
      this._text_208,
      this._text_209,
      this._el_210,
      this._text_211,
      this._el_212,
      this._text_213,
      this._text_214,
      this._el_215,
      this._text_216,
      this._el_217,
      this._text_218,
      this._el_219,
      this._text_220,
      this._el_221,
      this._text_222,
      this._el_223,
      this._text_224,
      this._el_225,
      this._text_226,
      this._text_227,
      this._el_228,
      this._text_229,
      this._el_230,
      this._text_231,
      this._text_232,
      this._el_233,
      this._text_234,
      this._el_235,
      this._text_236,
      this._el_237,
      this._text_238,
      this._el_239,
      this._text_240,
      this._el_241,
      this._el_242,
      this._text_243,
      this._el_244,
      this._el_245,
      this._text_246,
      this._text_247,
      this._el_248,
      this._text_249,
      this._el_250,
      this._text_251,
      this._text_252,
      this._el_253,
      this._text_254,
      this._el_255,
      this._text_256,
      this._el_257,
      this._text_258,
      this._el_259,
      this._el_260,
      this._text_261,
      this._el_262,
      this._el_263,
      this._text_264,
      this._el_265,
      this._el_266,
      this._text_267,
      this._text_268,
      this._el_269,
      this._text_270,
      this._el_271,
      this._text_272,
      this._text_273,
      this._el_274,
      this._text_275,
      this._el_276,
      this._text_277,
      this._el_278,
      this._text_279,
      this._el_280,
      this._el_281,
      this._text_282,
      this._el_283,
      this._el_284,
      this._text_285,
      this._el_286,
      this._el_287,
      this._text_288,
      this._text_289,
      this._el_290,
      this._text_291,
      this._el_292,
      this._text_293,
      this._text_294,
      this._el_295,
      this._text_296,
      this._el_297,
      this._el_298,
      this._text_299,
      this._el_300,
      this._el_301,
      this._text_302,
      this._el_303,
      this._text_304,
      this._el_305,
      this._el_306,
      this._text_307,
      this._el_308,
      this._el_309,
      this._text_310,
      this._text_311,
      this._el_312,
      this._text_313,
      this._el_314,
      this._text_315,
      this._text_316,
      this._el_317,
      this._el_318,
      this._text_319,
      this._el_320,
      this._el_321,
      this._text_322,
      this._el_323,
      this._el_324,
      this._text_325,
      this._el_326,
      this._el_327,
      this._text_328,
      this._el_329,
      this._el_330,
      this._text_331,
      this._el_332,
      this._el_333,
      this._text_334,
      this._text_335,
      this._el_336,
      this._text_337,
      this._el_338,
      this._text_339,
      this._text_340,
      this._el_341,
      this._el_342,
      this._text_343,
      this._el_344,
      this._el_345,
      this._text_346,
      this._el_347,
      this._el_348,
      this._text_349,
      this._el_350,
      this._el_351,
      this._text_352,
      this._el_353,
      this._el_354,
      this._text_355,
      this._el_356,
      this._el_357,
      this._text_358,
      this._text_359,
      this._text_360,
      this._text_361,
      this._text_362,
      this._el_363,
      this._text_364,
      this._text_365
    ]
    ,[],[]);
    return (null as any);
  }
}
export function viewFactory_CollisionTableComponent0(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement):import1.AppView<import3.CollisionTableComponent> {
  if ((renderType_CollisionTableComponent === (null as any))) { (renderType_CollisionTableComponent = viewUtils.createRenderComponentType('C:/Users/ketha/Documents/projects/web/unitystudygroup/assets/app/unitydocs/collision-table.component.html',0,import8.ViewEncapsulation.Emulated,styles_CollisionTableComponent,{})); }
  return new _View_CollisionTableComponent0(viewUtils,parentInjector,declarationEl);
}