/**
 * This file is generated by the Angular 2 template compiler.
 * Do not edit.
 */
 /* tslint:disable */

import * as import0 from '@angular/core/src/render/api';
import * as import1 from '@angular/core/src/linker/view';
import * as import2 from '@angular/core/src/linker/element';
import * as import3 from './signup-form.component';
import * as import4 from '@angular/core/src/linker/view_utils';
import * as import5 from '@angular/core/src/di/injector';
import * as import6 from '@angular/core/src/linker/view_type';
import * as import7 from '@angular/core/src/change_detection/change_detection';
import * as import8 from '@angular/forms/src/form_builder';
import * as import9 from './auth.service';
import * as import10 from '@angular/core/src/metadata/view';
import * as import11 from '@angular/core/src/linker/component_factory';
import * as import12 from '@angular/forms/src/directives/reactive_directives/form_group_directive';
import * as import13 from '@angular/forms/src/directives/ng_control_status';
import * as import14 from '@angular/forms/src/directives/default_value_accessor';
import * as import15 from '@angular/forms/src/directives/reactive_directives/form_control_name';
import * as import16 from '@angular/common/src/directives/ng_if';
import * as import17 from '@angular/core/src/linker/element_ref';
import * as import18 from '@angular/core/src/linker/template_ref';
import * as import19 from '@angular/forms/src/directives/control_value_accessor';
import * as import20 from '@angular/forms/src/directives/ng_control';
import * as import21 from '@angular/forms/src/directives/control_container';
var renderType_SignUpFormComponent_Host:import0.RenderComponentType = (null as any);
class _View_SignUpFormComponent_Host0 extends import1.AppView<any> {
  _el_0:any;
  /*private*/ _appEl_0:import2.AppElement;
  _SignUpFormComponent_0_4:import3.SignUpFormComponent;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement) {
    super(_View_SignUpFormComponent_Host0,renderType_SignUpFormComponent_Host,import6.ViewType.HOST,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import2.AppElement {
    this._el_0 = this.selectOrCreateHostElement('signup-form',rootSelector,(null as any));
    this._appEl_0 = new import2.AppElement(0,(null as any),this,this._el_0);
    var compView_0:any = viewFactory_SignUpFormComponent0(this.viewUtils,this.injector(0),this._appEl_0);
    this._SignUpFormComponent_0_4 = new import3.SignUpFormComponent(this.parentInjector.get(import8.FormBuilder),this.parentInjector.get(import9.AuthService));
    this._appEl_0.initComponent(this._SignUpFormComponent_0_4,[],compView_0);
    compView_0.create(this._SignUpFormComponent_0_4,this.projectableNodes,(null as any));
    this.init([].concat([this._el_0]),[this._el_0],[],[]);
    return this._appEl_0;
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import3.SignUpFormComponent) && (0 === requestNodeIndex))) { return this._SignUpFormComponent_0_4; }
    return notFoundResult;
  }
}
function viewFactory_SignUpFormComponent_Host0(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement):import1.AppView<any> {
  if ((renderType_SignUpFormComponent_Host === (null as any))) { (renderType_SignUpFormComponent_Host = viewUtils.createRenderComponentType('',0,import10.ViewEncapsulation.None,[],{})); }
  return new _View_SignUpFormComponent_Host0(viewUtils,parentInjector,declarationEl);
}
export const SignUpFormComponentNgFactory:import11.ComponentFactory<import3.SignUpFormComponent> = new import11.ComponentFactory<import3.SignUpFormComponent>('signup-form',viewFactory_SignUpFormComponent_Host0,import3.SignUpFormComponent);
const styles_SignUpFormComponent:any[] = ['.form-group[_ngcontent-%COMP%]{width: 30%; margin: 25px auto;}\n    .btn[_ngcontent-%COMP%]{margin-top: 20px;}'];
var renderType_SignUpFormComponent:import0.RenderComponentType = (null as any);
class _View_SignUpFormComponent0 extends import1.AppView<import3.SignUpFormComponent> {
  _el_0:any;
  _FormGroupDirective_0_3:import12.FormGroupDirective;
  _ControlContainer_0_4:any;
  _NgControlStatusGroup_0_5:import13.NgControlStatusGroup;
  _text_1:any;
  _el_2:any;
  _text_3:any;
  _el_4:any;
  _text_5:any;
  _text_6:any;
  _el_7:any;
  _text_8:any;
  _text_9:any;
  _el_10:any;
  _DefaultValueAccessor_10_3:import14.DefaultValueAccessor;
  _NG_VALUE_ACCESSOR_10_4:any[];
  _FormControlName_10_5:import15.FormControlName;
  _NgControl_10_6:any;
  _NgControlStatus_10_7:import13.NgControlStatus;
  _text_11:any;
  _anchor_12:any;
  /*private*/ _appEl_12:import2.AppElement;
  _TemplateRef_12_5:any;
  _NgIf_12_6:import16.NgIf;
  _text_13:any;
  _anchor_14:any;
  /*private*/ _appEl_14:import2.AppElement;
  _TemplateRef_14_5:any;
  _NgIf_14_6:import16.NgIf;
  _text_15:any;
  _text_16:any;
  _el_17:any;
  _text_18:any;
  _el_19:any;
  _text_20:any;
  _text_21:any;
  _el_22:any;
  _DefaultValueAccessor_22_3:import14.DefaultValueAccessor;
  _NG_VALUE_ACCESSOR_22_4:any[];
  _FormControlName_22_5:import15.FormControlName;
  _NgControl_22_6:any;
  _NgControlStatus_22_7:import13.NgControlStatus;
  _text_23:any;
  _anchor_24:any;
  /*private*/ _appEl_24:import2.AppElement;
  _TemplateRef_24_5:any;
  _NgIf_24_6:import16.NgIf;
  _text_25:any;
  _text_26:any;
  _el_27:any;
  _text_28:any;
  _el_29:any;
  _text_30:any;
  _text_31:any;
  _el_32:any;
  _DefaultValueAccessor_32_3:import14.DefaultValueAccessor;
  _NG_VALUE_ACCESSOR_32_4:any[];
  _FormControlName_32_5:import15.FormControlName;
  _NgControl_32_6:any;
  _NgControlStatus_32_7:import13.NgControlStatus;
  _text_33:any;
  _anchor_34:any;
  /*private*/ _appEl_34:import2.AppElement;
  _TemplateRef_34_5:any;
  _NgIf_34_6:import16.NgIf;
  _text_35:any;
  _text_36:any;
  _el_37:any;
  _text_38:any;
  _el_39:any;
  _text_40:any;
  _text_41:any;
  _el_42:any;
  _DefaultValueAccessor_42_3:import14.DefaultValueAccessor;
  _NG_VALUE_ACCESSOR_42_4:any[];
  _FormControlName_42_5:import15.FormControlName;
  _NgControl_42_6:any;
  _NgControlStatus_42_7:import13.NgControlStatus;
  _text_43:any;
  _anchor_44:any;
  /*private*/ _appEl_44:import2.AppElement;
  _TemplateRef_44_5:any;
  _NgIf_44_6:import16.NgIf;
  _text_45:any;
  _anchor_46:any;
  /*private*/ _appEl_46:import2.AppElement;
  _TemplateRef_46_5:any;
  _NgIf_46_6:import16.NgIf;
  _text_47:any;
  _el_48:any;
  _text_49:any;
  _text_50:any;
  _text_51:any;
  _text_52:any;
  /*private*/ _expr_3:any;
  /*private*/ _expr_4:any;
  /*private*/ _expr_5:any;
  /*private*/ _expr_6:any;
  /*private*/ _expr_7:any;
  /*private*/ _expr_8:any;
  /*private*/ _expr_9:any;
  /*private*/ _expr_12:any;
  /*private*/ _expr_13:any;
  /*private*/ _expr_14:any;
  /*private*/ _expr_15:any;
  /*private*/ _expr_16:any;
  /*private*/ _expr_17:any;
  /*private*/ _expr_18:any;
  /*private*/ _expr_19:any;
  /*private*/ _expr_20:any;
  /*private*/ _expr_23:any;
  /*private*/ _expr_24:any;
  /*private*/ _expr_25:any;
  /*private*/ _expr_26:any;
  /*private*/ _expr_27:any;
  /*private*/ _expr_28:any;
  /*private*/ _expr_29:any;
  /*private*/ _expr_30:any;
  /*private*/ _expr_33:any;
  /*private*/ _expr_34:any;
  /*private*/ _expr_35:any;
  /*private*/ _expr_36:any;
  /*private*/ _expr_37:any;
  /*private*/ _expr_38:any;
  /*private*/ _expr_39:any;
  /*private*/ _expr_40:any;
  /*private*/ _expr_43:any;
  /*private*/ _expr_44:any;
  /*private*/ _expr_45:any;
  /*private*/ _expr_46:any;
  /*private*/ _expr_47:any;
  /*private*/ _expr_48:any;
  /*private*/ _expr_49:any;
  /*private*/ _expr_50:any;
  /*private*/ _expr_51:any;
  /*private*/ _expr_52:any;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement) {
    super(_View_SignUpFormComponent0,renderType_SignUpFormComponent,import6.ViewType.COMPONENT,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import2.AppElement {
    const parentRenderNode:any = this.renderer.createViewRoot(this.declarationAppElement.nativeElement);
    this._el_0 = this.renderer.createElement(parentRenderNode,'form',(null as any));
    this._FormGroupDirective_0_3 = new import12.FormGroupDirective((null as any),(null as any));
    this._ControlContainer_0_4 = this._FormGroupDirective_0_3;
    this._NgControlStatusGroup_0_5 = new import13.NgControlStatusGroup(this._ControlContainer_0_4);
    this._text_1 = this.renderer.createText(this._el_0,'\n    ',(null as any));
    this._el_2 = this.renderer.createElement(this._el_0,'div',(null as any));
    this.renderer.setElementAttribute(this._el_2,'class','form-group container');
    this._text_3 = this.renderer.createText(this._el_2,'\n        ',(null as any));
    this._el_4 = this.renderer.createElement(this._el_2,'h1',(null as any));
    this.renderer.setElementAttribute(this._el_4,'style','text-align: center');
    this._text_5 = this.renderer.createText(this._el_4,'Sign Up',(null as any));
    this._text_6 = this.renderer.createText(this._el_2,'\n        ',(null as any));
    this._el_7 = this.renderer.createElement(this._el_2,'label',(null as any));
    this.renderer.setElementAttribute(this._el_7,'for','username');
    this._text_8 = this.renderer.createText(this._el_7,'Username',(null as any));
    this._text_9 = this.renderer.createText(this._el_2,'\n        ',(null as any));
    this._el_10 = this.renderer.createElement(this._el_2,'input',(null as any));
    this.renderer.setElementAttribute(this._el_10,'class','form-control');
    this.renderer.setElementAttribute(this._el_10,'formControlName','username');
    this.renderer.setElementAttribute(this._el_10,'id','username');
    this.renderer.setElementAttribute(this._el_10,'type','text');
    this._DefaultValueAccessor_10_3 = new import14.DefaultValueAccessor(this.renderer,new import17.ElementRef(this._el_10));
    this._NG_VALUE_ACCESSOR_10_4 = [this._DefaultValueAccessor_10_3];
    this._FormControlName_10_5 = new import15.FormControlName(this._ControlContainer_0_4,(null as any),(null as any),this._NG_VALUE_ACCESSOR_10_4);
    this._NgControl_10_6 = this._FormControlName_10_5;
    this._NgControlStatus_10_7 = new import13.NgControlStatus(this._NgControl_10_6);
    this._text_11 = this.renderer.createText(this._el_2,'\n        ',(null as any));
    this._anchor_12 = this.renderer.createTemplateAnchor(this._el_2,(null as any));
    this._appEl_12 = new import2.AppElement(12,2,this,this._anchor_12);
    this._TemplateRef_12_5 = new import18.TemplateRef_(this._appEl_12,viewFactory_SignUpFormComponent1);
    this._NgIf_12_6 = new import16.NgIf(this._appEl_12.vcRef,this._TemplateRef_12_5);
    this._text_13 = this.renderer.createText(this._el_2,'\n        ',(null as any));
    this._anchor_14 = this.renderer.createTemplateAnchor(this._el_2,(null as any));
    this._appEl_14 = new import2.AppElement(14,2,this,this._anchor_14);
    this._TemplateRef_14_5 = new import18.TemplateRef_(this._appEl_14,viewFactory_SignUpFormComponent2);
    this._NgIf_14_6 = new import16.NgIf(this._appEl_14.vcRef,this._TemplateRef_14_5);
    this._text_15 = this.renderer.createText(this._el_2,'\n    ',(null as any));
    this._text_16 = this.renderer.createText(this._el_0,'\n\n    ',(null as any));
    this._el_17 = this.renderer.createElement(this._el_0,'div',(null as any));
    this.renderer.setElementAttribute(this._el_17,'class','form-group container');
    this._text_18 = this.renderer.createText(this._el_17,'\n        ',(null as any));
    this._el_19 = this.renderer.createElement(this._el_17,'label',(null as any));
    this.renderer.setElementAttribute(this._el_19,'for','email');
    this._text_20 = this.renderer.createText(this._el_19,'Email',(null as any));
    this._text_21 = this.renderer.createText(this._el_17,'\n        ',(null as any));
    this._el_22 = this.renderer.createElement(this._el_17,'input',(null as any));
    this.renderer.setElementAttribute(this._el_22,'class','form-control');
    this.renderer.setElementAttribute(this._el_22,'formControlName','email');
    this.renderer.setElementAttribute(this._el_22,'id','email');
    this.renderer.setElementAttribute(this._el_22,'type','text');
    this._DefaultValueAccessor_22_3 = new import14.DefaultValueAccessor(this.renderer,new import17.ElementRef(this._el_22));
    this._NG_VALUE_ACCESSOR_22_4 = [this._DefaultValueAccessor_22_3];
    this._FormControlName_22_5 = new import15.FormControlName(this._ControlContainer_0_4,(null as any),(null as any),this._NG_VALUE_ACCESSOR_22_4);
    this._NgControl_22_6 = this._FormControlName_22_5;
    this._NgControlStatus_22_7 = new import13.NgControlStatus(this._NgControl_22_6);
    this._text_23 = this.renderer.createText(this._el_17,'\n        ',(null as any));
    this._anchor_24 = this.renderer.createTemplateAnchor(this._el_17,(null as any));
    this._appEl_24 = new import2.AppElement(24,17,this,this._anchor_24);
    this._TemplateRef_24_5 = new import18.TemplateRef_(this._appEl_24,viewFactory_SignUpFormComponent6);
    this._NgIf_24_6 = new import16.NgIf(this._appEl_24.vcRef,this._TemplateRef_24_5);
    this._text_25 = this.renderer.createText(this._el_17,'\n    ',(null as any));
    this._text_26 = this.renderer.createText(this._el_0,'\n\n    ',(null as any));
    this._el_27 = this.renderer.createElement(this._el_0,'div',(null as any));
    this.renderer.setElementAttribute(this._el_27,'class','form-group container');
    this._text_28 = this.renderer.createText(this._el_27,'\n        ',(null as any));
    this._el_29 = this.renderer.createElement(this._el_27,'label',(null as any));
    this.renderer.setElementAttribute(this._el_29,'for','password');
    this._text_30 = this.renderer.createText(this._el_29,'New Password',(null as any));
    this._text_31 = this.renderer.createText(this._el_27,'\n        ',(null as any));
    this._el_32 = this.renderer.createElement(this._el_27,'input',(null as any));
    this.renderer.setElementAttribute(this._el_32,'class','form-control');
    this.renderer.setElementAttribute(this._el_32,'formControlName','password');
    this.renderer.setElementAttribute(this._el_32,'id','password');
    this.renderer.setElementAttribute(this._el_32,'type','password');
    this._DefaultValueAccessor_32_3 = new import14.DefaultValueAccessor(this.renderer,new import17.ElementRef(this._el_32));
    this._NG_VALUE_ACCESSOR_32_4 = [this._DefaultValueAccessor_32_3];
    this._FormControlName_32_5 = new import15.FormControlName(this._ControlContainer_0_4,(null as any),(null as any),this._NG_VALUE_ACCESSOR_32_4);
    this._NgControl_32_6 = this._FormControlName_32_5;
    this._NgControlStatus_32_7 = new import13.NgControlStatus(this._NgControl_32_6);
    this._text_33 = this.renderer.createText(this._el_27,'\n        ',(null as any));
    this._anchor_34 = this.renderer.createTemplateAnchor(this._el_27,(null as any));
    this._appEl_34 = new import2.AppElement(34,27,this,this._anchor_34);
    this._TemplateRef_34_5 = new import18.TemplateRef_(this._appEl_34,viewFactory_SignUpFormComponent9);
    this._NgIf_34_6 = new import16.NgIf(this._appEl_34.vcRef,this._TemplateRef_34_5);
    this._text_35 = this.renderer.createText(this._el_27,'\n    ',(null as any));
    this._text_36 = this.renderer.createText(this._el_0,'\n\n    ',(null as any));
    this._el_37 = this.renderer.createElement(this._el_0,'div',(null as any));
    this.renderer.setElementAttribute(this._el_37,'class','form-group container');
    this._text_38 = this.renderer.createText(this._el_37,'\n        ',(null as any));
    this._el_39 = this.renderer.createElement(this._el_37,'label',(null as any));
    this.renderer.setElementAttribute(this._el_39,'for','confirmPassword');
    this._text_40 = this.renderer.createText(this._el_39,'Confirm Password',(null as any));
    this._text_41 = this.renderer.createText(this._el_37,'\n        ',(null as any));
    this._el_42 = this.renderer.createElement(this._el_37,'input',(null as any));
    this.renderer.setElementAttribute(this._el_42,'class','form-control');
    this.renderer.setElementAttribute(this._el_42,'formControlName','confirmPassword');
    this.renderer.setElementAttribute(this._el_42,'id','confirmPassword');
    this.renderer.setElementAttribute(this._el_42,'type','password');
    this._DefaultValueAccessor_42_3 = new import14.DefaultValueAccessor(this.renderer,new import17.ElementRef(this._el_42));
    this._NG_VALUE_ACCESSOR_42_4 = [this._DefaultValueAccessor_42_3];
    this._FormControlName_42_5 = new import15.FormControlName(this._ControlContainer_0_4,(null as any),(null as any),this._NG_VALUE_ACCESSOR_42_4);
    this._NgControl_42_6 = this._FormControlName_42_5;
    this._NgControlStatus_42_7 = new import13.NgControlStatus(this._NgControl_42_6);
    this._text_43 = this.renderer.createText(this._el_37,'\n        ',(null as any));
    this._anchor_44 = this.renderer.createTemplateAnchor(this._el_37,(null as any));
    this._appEl_44 = new import2.AppElement(44,37,this,this._anchor_44);
    this._TemplateRef_44_5 = new import18.TemplateRef_(this._appEl_44,viewFactory_SignUpFormComponent12);
    this._NgIf_44_6 = new import16.NgIf(this._appEl_44.vcRef,this._TemplateRef_44_5);
    this._text_45 = this.renderer.createText(this._el_37,'\n        ',(null as any));
    this._anchor_46 = this.renderer.createTemplateAnchor(this._el_37,(null as any));
    this._appEl_46 = new import2.AppElement(46,37,this,this._anchor_46);
    this._TemplateRef_46_5 = new import18.TemplateRef_(this._appEl_46,viewFactory_SignUpFormComponent14);
    this._NgIf_46_6 = new import16.NgIf(this._appEl_46.vcRef,this._TemplateRef_46_5);
    this._text_47 = this.renderer.createText(this._el_37,'\n\n    ',(null as any));
    this._el_48 = this.renderer.createElement(this._el_37,'button',(null as any));
    this.renderer.setElementAttribute(this._el_48,'class','btn btn-primary btn-lg btn-block');
    this._text_49 = this.renderer.createText(this._el_48,'Sign Up',(null as any));
    this._text_50 = this.renderer.createText(this._el_37,'\n    ',(null as any));
    this._text_51 = this.renderer.createText(this._el_0,'\n',(null as any));
    this._text_52 = this.renderer.createText(parentRenderNode,'\n',(null as any));
    var disposable_0:Function = this.renderer.listen(this._el_0,'ngSubmit',this.eventHandler(this._handle_ngSubmit_0_0.bind(this)));
    var disposable_1:Function = this.renderer.listen(this._el_0,'submit',this.eventHandler(this._handle_submit_0_1.bind(this)));
    var disposable_2:Function = this.renderer.listen(this._el_0,'reset',this.eventHandler(this._handle_reset_0_2.bind(this)));
    this._expr_3 = import7.UNINITIALIZED;
    const subscription_0:any = this._FormGroupDirective_0_3.ngSubmit.subscribe(this.eventHandler(this._handle_ngSubmit_0_0.bind(this)));
    this._expr_4 = import7.UNINITIALIZED;
    this._expr_5 = import7.UNINITIALIZED;
    this._expr_6 = import7.UNINITIALIZED;
    this._expr_7 = import7.UNINITIALIZED;
    this._expr_8 = import7.UNINITIALIZED;
    this._expr_9 = import7.UNINITIALIZED;
    var disposable_3:Function = this.renderer.listen(this._el_10,'input',this.eventHandler(this._handle_input_10_0.bind(this)));
    var disposable_4:Function = this.renderer.listen(this._el_10,'blur',this.eventHandler(this._handle_blur_10_1.bind(this)));
    this._expr_12 = import7.UNINITIALIZED;
    this._expr_13 = import7.UNINITIALIZED;
    this._expr_14 = import7.UNINITIALIZED;
    this._expr_15 = import7.UNINITIALIZED;
    this._expr_16 = import7.UNINITIALIZED;
    this._expr_17 = import7.UNINITIALIZED;
    this._expr_18 = import7.UNINITIALIZED;
    this._expr_19 = import7.UNINITIALIZED;
    this._expr_20 = import7.UNINITIALIZED;
    var disposable_5:Function = this.renderer.listen(this._el_22,'input',this.eventHandler(this._handle_input_22_0.bind(this)));
    var disposable_6:Function = this.renderer.listen(this._el_22,'blur',this.eventHandler(this._handle_blur_22_1.bind(this)));
    this._expr_23 = import7.UNINITIALIZED;
    this._expr_24 = import7.UNINITIALIZED;
    this._expr_25 = import7.UNINITIALIZED;
    this._expr_26 = import7.UNINITIALIZED;
    this._expr_27 = import7.UNINITIALIZED;
    this._expr_28 = import7.UNINITIALIZED;
    this._expr_29 = import7.UNINITIALIZED;
    this._expr_30 = import7.UNINITIALIZED;
    var disposable_7:Function = this.renderer.listen(this._el_32,'input',this.eventHandler(this._handle_input_32_0.bind(this)));
    var disposable_8:Function = this.renderer.listen(this._el_32,'blur',this.eventHandler(this._handle_blur_32_1.bind(this)));
    this._expr_33 = import7.UNINITIALIZED;
    this._expr_34 = import7.UNINITIALIZED;
    this._expr_35 = import7.UNINITIALIZED;
    this._expr_36 = import7.UNINITIALIZED;
    this._expr_37 = import7.UNINITIALIZED;
    this._expr_38 = import7.UNINITIALIZED;
    this._expr_39 = import7.UNINITIALIZED;
    this._expr_40 = import7.UNINITIALIZED;
    var disposable_9:Function = this.renderer.listen(this._el_42,'input',this.eventHandler(this._handle_input_42_0.bind(this)));
    var disposable_10:Function = this.renderer.listen(this._el_42,'blur',this.eventHandler(this._handle_blur_42_1.bind(this)));
    this._expr_43 = import7.UNINITIALIZED;
    this._expr_44 = import7.UNINITIALIZED;
    this._expr_45 = import7.UNINITIALIZED;
    this._expr_46 = import7.UNINITIALIZED;
    this._expr_47 = import7.UNINITIALIZED;
    this._expr_48 = import7.UNINITIALIZED;
    this._expr_49 = import7.UNINITIALIZED;
    this._expr_50 = import7.UNINITIALIZED;
    this._expr_51 = import7.UNINITIALIZED;
    this._expr_52 = import7.UNINITIALIZED;
    this.init([],[
      this._el_0,
      this._text_1,
      this._el_2,
      this._text_3,
      this._el_4,
      this._text_5,
      this._text_6,
      this._el_7,
      this._text_8,
      this._text_9,
      this._el_10,
      this._text_11,
      this._anchor_12,
      this._text_13,
      this._anchor_14,
      this._text_15,
      this._text_16,
      this._el_17,
      this._text_18,
      this._el_19,
      this._text_20,
      this._text_21,
      this._el_22,
      this._text_23,
      this._anchor_24,
      this._text_25,
      this._text_26,
      this._el_27,
      this._text_28,
      this._el_29,
      this._text_30,
      this._text_31,
      this._el_32,
      this._text_33,
      this._anchor_34,
      this._text_35,
      this._text_36,
      this._el_37,
      this._text_38,
      this._el_39,
      this._text_40,
      this._text_41,
      this._el_42,
      this._text_43,
      this._anchor_44,
      this._text_45,
      this._anchor_46,
      this._text_47,
      this._el_48,
      this._text_49,
      this._text_50,
      this._text_51,
      this._text_52
    ]
    ,[
      disposable_0,
      disposable_1,
      disposable_2,
      disposable_3,
      disposable_4,
      disposable_5,
      disposable_6,
      disposable_7,
      disposable_8,
      disposable_9,
      disposable_10
    ]
    ,[subscription_0]);
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import14.DefaultValueAccessor) && (10 === requestNodeIndex))) { return this._DefaultValueAccessor_10_3; }
    if (((token === import19.NG_VALUE_ACCESSOR) && (10 === requestNodeIndex))) { return this._NG_VALUE_ACCESSOR_10_4; }
    if (((token === import15.FormControlName) && (10 === requestNodeIndex))) { return this._FormControlName_10_5; }
    if (((token === import20.NgControl) && (10 === requestNodeIndex))) { return this._NgControl_10_6; }
    if (((token === import13.NgControlStatus) && (10 === requestNodeIndex))) { return this._NgControlStatus_10_7; }
    if (((token === import18.TemplateRef) && (12 === requestNodeIndex))) { return this._TemplateRef_12_5; }
    if (((token === import16.NgIf) && (12 === requestNodeIndex))) { return this._NgIf_12_6; }
    if (((token === import18.TemplateRef) && (14 === requestNodeIndex))) { return this._TemplateRef_14_5; }
    if (((token === import16.NgIf) && (14 === requestNodeIndex))) { return this._NgIf_14_6; }
    if (((token === import14.DefaultValueAccessor) && (22 === requestNodeIndex))) { return this._DefaultValueAccessor_22_3; }
    if (((token === import19.NG_VALUE_ACCESSOR) && (22 === requestNodeIndex))) { return this._NG_VALUE_ACCESSOR_22_4; }
    if (((token === import15.FormControlName) && (22 === requestNodeIndex))) { return this._FormControlName_22_5; }
    if (((token === import20.NgControl) && (22 === requestNodeIndex))) { return this._NgControl_22_6; }
    if (((token === import13.NgControlStatus) && (22 === requestNodeIndex))) { return this._NgControlStatus_22_7; }
    if (((token === import18.TemplateRef) && (24 === requestNodeIndex))) { return this._TemplateRef_24_5; }
    if (((token === import16.NgIf) && (24 === requestNodeIndex))) { return this._NgIf_24_6; }
    if (((token === import14.DefaultValueAccessor) && (32 === requestNodeIndex))) { return this._DefaultValueAccessor_32_3; }
    if (((token === import19.NG_VALUE_ACCESSOR) && (32 === requestNodeIndex))) { return this._NG_VALUE_ACCESSOR_32_4; }
    if (((token === import15.FormControlName) && (32 === requestNodeIndex))) { return this._FormControlName_32_5; }
    if (((token === import20.NgControl) && (32 === requestNodeIndex))) { return this._NgControl_32_6; }
    if (((token === import13.NgControlStatus) && (32 === requestNodeIndex))) { return this._NgControlStatus_32_7; }
    if (((token === import18.TemplateRef) && (34 === requestNodeIndex))) { return this._TemplateRef_34_5; }
    if (((token === import16.NgIf) && (34 === requestNodeIndex))) { return this._NgIf_34_6; }
    if (((token === import14.DefaultValueAccessor) && (42 === requestNodeIndex))) { return this._DefaultValueAccessor_42_3; }
    if (((token === import19.NG_VALUE_ACCESSOR) && (42 === requestNodeIndex))) { return this._NG_VALUE_ACCESSOR_42_4; }
    if (((token === import15.FormControlName) && (42 === requestNodeIndex))) { return this._FormControlName_42_5; }
    if (((token === import20.NgControl) && (42 === requestNodeIndex))) { return this._NgControl_42_6; }
    if (((token === import13.NgControlStatus) && (42 === requestNodeIndex))) { return this._NgControlStatus_42_7; }
    if (((token === import18.TemplateRef) && (44 === requestNodeIndex))) { return this._TemplateRef_44_5; }
    if (((token === import16.NgIf) && (44 === requestNodeIndex))) { return this._NgIf_44_6; }
    if (((token === import18.TemplateRef) && (46 === requestNodeIndex))) { return this._TemplateRef_46_5; }
    if (((token === import16.NgIf) && (46 === requestNodeIndex))) { return this._NgIf_46_6; }
    if (((token === import12.FormGroupDirective) && ((0 <= requestNodeIndex) && (requestNodeIndex <= 51)))) { return this._FormGroupDirective_0_3; }
    if (((token === import21.ControlContainer) && ((0 <= requestNodeIndex) && (requestNodeIndex <= 51)))) { return this._ControlContainer_0_4; }
    if (((token === import13.NgControlStatusGroup) && ((0 <= requestNodeIndex) && (requestNodeIndex <= 51)))) { return this._NgControlStatusGroup_0_5; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    var changes:{[key: string]:import7.SimpleChange} = (null as any);
    changes = (null as any);
    const currVal_3:any = this.context.form;
    if (import4.checkBinding(throwOnChange,this._expr_3,currVal_3)) {
      this._FormGroupDirective_0_3.form = currVal_3;
      if ((changes === (null as any))) { (changes = {}); }
      changes['form'] = new import7.SimpleChange(this._expr_3,currVal_3);
      this._expr_3 = currVal_3;
    }
    if ((changes !== (null as any))) { this._FormGroupDirective_0_3.ngOnChanges(changes); }
    changes = (null as any);
    const currVal_12:any = 'username';
    if (import4.checkBinding(throwOnChange,this._expr_12,currVal_12)) {
      this._FormControlName_10_5.name = currVal_12;
      if ((changes === (null as any))) { (changes = {}); }
      changes['name'] = new import7.SimpleChange(this._expr_12,currVal_12);
      this._expr_12 = currVal_12;
    }
    if ((changes !== (null as any))) { this._FormControlName_10_5.ngOnChanges(changes); }
    const currVal_19:any = this.context.form.get('username').pending;
    if (import4.checkBinding(throwOnChange,this._expr_19,currVal_19)) {
      this._NgIf_12_6.ngIf = currVal_19;
      this._expr_19 = currVal_19;
    }
    const currVal_20:any = (this.context.form.get('username').touched && this.context.form.get('username').errors);
    if (import4.checkBinding(throwOnChange,this._expr_20,currVal_20)) {
      this._NgIf_14_6.ngIf = currVal_20;
      this._expr_20 = currVal_20;
    }
    changes = (null as any);
    const currVal_23:any = 'email';
    if (import4.checkBinding(throwOnChange,this._expr_23,currVal_23)) {
      this._FormControlName_22_5.name = currVal_23;
      if ((changes === (null as any))) { (changes = {}); }
      changes['name'] = new import7.SimpleChange(this._expr_23,currVal_23);
      this._expr_23 = currVal_23;
    }
    if ((changes !== (null as any))) { this._FormControlName_22_5.ngOnChanges(changes); }
    const currVal_30:any = (this.context.form.get('email').touched && !this.context.form.get('email').valid);
    if (import4.checkBinding(throwOnChange,this._expr_30,currVal_30)) {
      this._NgIf_24_6.ngIf = currVal_30;
      this._expr_30 = currVal_30;
    }
    changes = (null as any);
    const currVal_33:any = 'password';
    if (import4.checkBinding(throwOnChange,this._expr_33,currVal_33)) {
      this._FormControlName_32_5.name = currVal_33;
      if ((changes === (null as any))) { (changes = {}); }
      changes['name'] = new import7.SimpleChange(this._expr_33,currVal_33);
      this._expr_33 = currVal_33;
    }
    if ((changes !== (null as any))) { this._FormControlName_32_5.ngOnChanges(changes); }
    const currVal_40:any = (this.context.form.get('password').touched && !this.context.form.get('password').valid);
    if (import4.checkBinding(throwOnChange,this._expr_40,currVal_40)) {
      this._NgIf_34_6.ngIf = currVal_40;
      this._expr_40 = currVal_40;
    }
    changes = (null as any);
    const currVal_43:any = 'confirmPassword';
    if (import4.checkBinding(throwOnChange,this._expr_43,currVal_43)) {
      this._FormControlName_42_5.name = currVal_43;
      if ((changes === (null as any))) { (changes = {}); }
      changes['name'] = new import7.SimpleChange(this._expr_43,currVal_43);
      this._expr_43 = currVal_43;
    }
    if ((changes !== (null as any))) { this._FormControlName_42_5.ngOnChanges(changes); }
    const currVal_50:any = (this.context.form.get('confirmPassword').touched && !this.context.form.get('confirmPassword').valid);
    if (import4.checkBinding(throwOnChange,this._expr_50,currVal_50)) {
      this._NgIf_44_6.ngIf = currVal_50;
      this._expr_50 = currVal_50;
    }
    const currVal_51:any = (this.context.form.get('confirmPassword').touched && this.context.form.hasError('passwordsShouldMatch'));
    if (import4.checkBinding(throwOnChange,this._expr_51,currVal_51)) {
      this._NgIf_46_6.ngIf = currVal_51;
      this._expr_51 = currVal_51;
    }
    this.detectContentChildrenChanges(throwOnChange);
    const currVal_4:any = this._NgControlStatusGroup_0_5.ngClassUntouched;
    if (import4.checkBinding(throwOnChange,this._expr_4,currVal_4)) {
      this.renderer.setElementClass(this._el_0,'ng-untouched',currVal_4);
      this._expr_4 = currVal_4;
    }
    const currVal_5:any = this._NgControlStatusGroup_0_5.ngClassTouched;
    if (import4.checkBinding(throwOnChange,this._expr_5,currVal_5)) {
      this.renderer.setElementClass(this._el_0,'ng-touched',currVal_5);
      this._expr_5 = currVal_5;
    }
    const currVal_6:any = this._NgControlStatusGroup_0_5.ngClassPristine;
    if (import4.checkBinding(throwOnChange,this._expr_6,currVal_6)) {
      this.renderer.setElementClass(this._el_0,'ng-pristine',currVal_6);
      this._expr_6 = currVal_6;
    }
    const currVal_7:any = this._NgControlStatusGroup_0_5.ngClassDirty;
    if (import4.checkBinding(throwOnChange,this._expr_7,currVal_7)) {
      this.renderer.setElementClass(this._el_0,'ng-dirty',currVal_7);
      this._expr_7 = currVal_7;
    }
    const currVal_8:any = this._NgControlStatusGroup_0_5.ngClassValid;
    if (import4.checkBinding(throwOnChange,this._expr_8,currVal_8)) {
      this.renderer.setElementClass(this._el_0,'ng-valid',currVal_8);
      this._expr_8 = currVal_8;
    }
    const currVal_9:any = this._NgControlStatusGroup_0_5.ngClassInvalid;
    if (import4.checkBinding(throwOnChange,this._expr_9,currVal_9)) {
      this.renderer.setElementClass(this._el_0,'ng-invalid',currVal_9);
      this._expr_9 = currVal_9;
    }
    const currVal_13:any = this._NgControlStatus_10_7.ngClassUntouched;
    if (import4.checkBinding(throwOnChange,this._expr_13,currVal_13)) {
      this.renderer.setElementClass(this._el_10,'ng-untouched',currVal_13);
      this._expr_13 = currVal_13;
    }
    const currVal_14:any = this._NgControlStatus_10_7.ngClassTouched;
    if (import4.checkBinding(throwOnChange,this._expr_14,currVal_14)) {
      this.renderer.setElementClass(this._el_10,'ng-touched',currVal_14);
      this._expr_14 = currVal_14;
    }
    const currVal_15:any = this._NgControlStatus_10_7.ngClassPristine;
    if (import4.checkBinding(throwOnChange,this._expr_15,currVal_15)) {
      this.renderer.setElementClass(this._el_10,'ng-pristine',currVal_15);
      this._expr_15 = currVal_15;
    }
    const currVal_16:any = this._NgControlStatus_10_7.ngClassDirty;
    if (import4.checkBinding(throwOnChange,this._expr_16,currVal_16)) {
      this.renderer.setElementClass(this._el_10,'ng-dirty',currVal_16);
      this._expr_16 = currVal_16;
    }
    const currVal_17:any = this._NgControlStatus_10_7.ngClassValid;
    if (import4.checkBinding(throwOnChange,this._expr_17,currVal_17)) {
      this.renderer.setElementClass(this._el_10,'ng-valid',currVal_17);
      this._expr_17 = currVal_17;
    }
    const currVal_18:any = this._NgControlStatus_10_7.ngClassInvalid;
    if (import4.checkBinding(throwOnChange,this._expr_18,currVal_18)) {
      this.renderer.setElementClass(this._el_10,'ng-invalid',currVal_18);
      this._expr_18 = currVal_18;
    }
    const currVal_24:any = this._NgControlStatus_22_7.ngClassUntouched;
    if (import4.checkBinding(throwOnChange,this._expr_24,currVal_24)) {
      this.renderer.setElementClass(this._el_22,'ng-untouched',currVal_24);
      this._expr_24 = currVal_24;
    }
    const currVal_25:any = this._NgControlStatus_22_7.ngClassTouched;
    if (import4.checkBinding(throwOnChange,this._expr_25,currVal_25)) {
      this.renderer.setElementClass(this._el_22,'ng-touched',currVal_25);
      this._expr_25 = currVal_25;
    }
    const currVal_26:any = this._NgControlStatus_22_7.ngClassPristine;
    if (import4.checkBinding(throwOnChange,this._expr_26,currVal_26)) {
      this.renderer.setElementClass(this._el_22,'ng-pristine',currVal_26);
      this._expr_26 = currVal_26;
    }
    const currVal_27:any = this._NgControlStatus_22_7.ngClassDirty;
    if (import4.checkBinding(throwOnChange,this._expr_27,currVal_27)) {
      this.renderer.setElementClass(this._el_22,'ng-dirty',currVal_27);
      this._expr_27 = currVal_27;
    }
    const currVal_28:any = this._NgControlStatus_22_7.ngClassValid;
    if (import4.checkBinding(throwOnChange,this._expr_28,currVal_28)) {
      this.renderer.setElementClass(this._el_22,'ng-valid',currVal_28);
      this._expr_28 = currVal_28;
    }
    const currVal_29:any = this._NgControlStatus_22_7.ngClassInvalid;
    if (import4.checkBinding(throwOnChange,this._expr_29,currVal_29)) {
      this.renderer.setElementClass(this._el_22,'ng-invalid',currVal_29);
      this._expr_29 = currVal_29;
    }
    const currVal_34:any = this._NgControlStatus_32_7.ngClassUntouched;
    if (import4.checkBinding(throwOnChange,this._expr_34,currVal_34)) {
      this.renderer.setElementClass(this._el_32,'ng-untouched',currVal_34);
      this._expr_34 = currVal_34;
    }
    const currVal_35:any = this._NgControlStatus_32_7.ngClassTouched;
    if (import4.checkBinding(throwOnChange,this._expr_35,currVal_35)) {
      this.renderer.setElementClass(this._el_32,'ng-touched',currVal_35);
      this._expr_35 = currVal_35;
    }
    const currVal_36:any = this._NgControlStatus_32_7.ngClassPristine;
    if (import4.checkBinding(throwOnChange,this._expr_36,currVal_36)) {
      this.renderer.setElementClass(this._el_32,'ng-pristine',currVal_36);
      this._expr_36 = currVal_36;
    }
    const currVal_37:any = this._NgControlStatus_32_7.ngClassDirty;
    if (import4.checkBinding(throwOnChange,this._expr_37,currVal_37)) {
      this.renderer.setElementClass(this._el_32,'ng-dirty',currVal_37);
      this._expr_37 = currVal_37;
    }
    const currVal_38:any = this._NgControlStatus_32_7.ngClassValid;
    if (import4.checkBinding(throwOnChange,this._expr_38,currVal_38)) {
      this.renderer.setElementClass(this._el_32,'ng-valid',currVal_38);
      this._expr_38 = currVal_38;
    }
    const currVal_39:any = this._NgControlStatus_32_7.ngClassInvalid;
    if (import4.checkBinding(throwOnChange,this._expr_39,currVal_39)) {
      this.renderer.setElementClass(this._el_32,'ng-invalid',currVal_39);
      this._expr_39 = currVal_39;
    }
    const currVal_44:any = this._NgControlStatus_42_7.ngClassUntouched;
    if (import4.checkBinding(throwOnChange,this._expr_44,currVal_44)) {
      this.renderer.setElementClass(this._el_42,'ng-untouched',currVal_44);
      this._expr_44 = currVal_44;
    }
    const currVal_45:any = this._NgControlStatus_42_7.ngClassTouched;
    if (import4.checkBinding(throwOnChange,this._expr_45,currVal_45)) {
      this.renderer.setElementClass(this._el_42,'ng-touched',currVal_45);
      this._expr_45 = currVal_45;
    }
    const currVal_46:any = this._NgControlStatus_42_7.ngClassPristine;
    if (import4.checkBinding(throwOnChange,this._expr_46,currVal_46)) {
      this.renderer.setElementClass(this._el_42,'ng-pristine',currVal_46);
      this._expr_46 = currVal_46;
    }
    const currVal_47:any = this._NgControlStatus_42_7.ngClassDirty;
    if (import4.checkBinding(throwOnChange,this._expr_47,currVal_47)) {
      this.renderer.setElementClass(this._el_42,'ng-dirty',currVal_47);
      this._expr_47 = currVal_47;
    }
    const currVal_48:any = this._NgControlStatus_42_7.ngClassValid;
    if (import4.checkBinding(throwOnChange,this._expr_48,currVal_48)) {
      this.renderer.setElementClass(this._el_42,'ng-valid',currVal_48);
      this._expr_48 = currVal_48;
    }
    const currVal_49:any = this._NgControlStatus_42_7.ngClassInvalid;
    if (import4.checkBinding(throwOnChange,this._expr_49,currVal_49)) {
      this.renderer.setElementClass(this._el_42,'ng-invalid',currVal_49);
      this._expr_49 = currVal_49;
    }
    const currVal_52:boolean = !this.context.form.valid;
    if (import4.checkBinding(throwOnChange,this._expr_52,currVal_52)) {
      this.renderer.setElementProperty(this._el_48,'disabled',currVal_52);
      this._expr_52 = currVal_52;
    }
    this.detectViewChildrenChanges(throwOnChange);
  }
  destroyInternal():void {
    this._FormControlName_10_5.ngOnDestroy();
    this._FormControlName_22_5.ngOnDestroy();
    this._FormControlName_32_5.ngOnDestroy();
    this._FormControlName_42_5.ngOnDestroy();
  }
  private _handle_ngSubmit_0_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this.context.onSubmit()) !== false);
    return (true && pd_0);
  }
  private _handle_submit_0_1($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this._FormGroupDirective_0_3.onSubmit()) !== false);
    return (true && pd_0);
  }
  private _handle_reset_0_2($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this._FormGroupDirective_0_3.onReset()) !== false);
    return (true && pd_0);
  }
  private _handle_input_10_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this._DefaultValueAccessor_10_3.onChange($event.target.value)) !== false);
    return (true && pd_0);
  }
  private _handle_blur_10_1($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this._DefaultValueAccessor_10_3.onTouched()) !== false);
    return (true && pd_0);
  }
  private _handle_input_22_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this._DefaultValueAccessor_22_3.onChange($event.target.value)) !== false);
    return (true && pd_0);
  }
  private _handle_blur_22_1($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this._DefaultValueAccessor_22_3.onTouched()) !== false);
    return (true && pd_0);
  }
  private _handle_input_32_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this._DefaultValueAccessor_32_3.onChange($event.target.value)) !== false);
    return (true && pd_0);
  }
  private _handle_blur_32_1($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this._DefaultValueAccessor_32_3.onTouched()) !== false);
    return (true && pd_0);
  }
  private _handle_input_42_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this._DefaultValueAccessor_42_3.onChange($event.target.value)) !== false);
    return (true && pd_0);
  }
  private _handle_blur_42_1($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this._DefaultValueAccessor_42_3.onTouched()) !== false);
    return (true && pd_0);
  }
}
export function viewFactory_SignUpFormComponent0(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement):import1.AppView<import3.SignUpFormComponent> {
  if ((renderType_SignUpFormComponent === (null as any))) { (renderType_SignUpFormComponent = viewUtils.createRenderComponentType('C:/Users/ketha/Desktop/projects/web/unitystudygroup/assets/app/auth/signup-form.component.html',0,import10.ViewEncapsulation.Emulated,styles_SignUpFormComponent,{})); }
  return new _View_SignUpFormComponent0(viewUtils,parentInjector,declarationEl);
}
class _View_SignUpFormComponent1 extends import1.AppView<any> {
  _el_0:any;
  _text_1:any;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement) {
    super(_View_SignUpFormComponent1,renderType_SignUpFormComponent,import6.ViewType.EMBEDDED,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import2.AppElement {
    this._el_0 = this.renderer.createElement((null as any),'div',(null as any));
    this._text_1 = this.renderer.createText(this._el_0,'Checking for uniqueness...',(null as any));
    this.init([].concat([this._el_0]),[
      this._el_0,
      this._text_1
    ]
    ,[],[]);
    return (null as any);
  }
}
function viewFactory_SignUpFormComponent1(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement):import1.AppView<any> {
  return new _View_SignUpFormComponent1(viewUtils,parentInjector,declarationEl);
}
class _View_SignUpFormComponent2 extends import1.AppView<any> {
  _el_0:any;
  _text_1:any;
  _anchor_2:any;
  /*private*/ _appEl_2:import2.AppElement;
  _TemplateRef_2_5:any;
  _NgIf_2_6:import16.NgIf;
  _text_3:any;
  _anchor_4:any;
  /*private*/ _appEl_4:import2.AppElement;
  _TemplateRef_4_5:any;
  _NgIf_4_6:import16.NgIf;
  _text_5:any;
  _anchor_6:any;
  /*private*/ _appEl_6:import2.AppElement;
  _TemplateRef_6_5:any;
  _NgIf_6_6:import16.NgIf;
  _text_7:any;
  /*private*/ _expr_0:any;
  /*private*/ _expr_1:any;
  /*private*/ _expr_2:any;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement) {
    super(_View_SignUpFormComponent2,renderType_SignUpFormComponent,import6.ViewType.EMBEDDED,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import2.AppElement {
    this._el_0 = this.renderer.createElement((null as any),'div',(null as any));
    this._text_1 = this.renderer.createText(this._el_0,'\n            ',(null as any));
    this._anchor_2 = this.renderer.createTemplateAnchor(this._el_0,(null as any));
    this._appEl_2 = new import2.AppElement(2,0,this,this._anchor_2);
    this._TemplateRef_2_5 = new import18.TemplateRef_(this._appEl_2,viewFactory_SignUpFormComponent3);
    this._NgIf_2_6 = new import16.NgIf(this._appEl_2.vcRef,this._TemplateRef_2_5);
    this._text_3 = this.renderer.createText(this._el_0,'\n            ',(null as any));
    this._anchor_4 = this.renderer.createTemplateAnchor(this._el_0,(null as any));
    this._appEl_4 = new import2.AppElement(4,0,this,this._anchor_4);
    this._TemplateRef_4_5 = new import18.TemplateRef_(this._appEl_4,viewFactory_SignUpFormComponent4);
    this._NgIf_4_6 = new import16.NgIf(this._appEl_4.vcRef,this._TemplateRef_4_5);
    this._text_5 = this.renderer.createText(this._el_0,'\n            ',(null as any));
    this._anchor_6 = this.renderer.createTemplateAnchor(this._el_0,(null as any));
    this._appEl_6 = new import2.AppElement(6,0,this,this._anchor_6);
    this._TemplateRef_6_5 = new import18.TemplateRef_(this._appEl_6,viewFactory_SignUpFormComponent5);
    this._NgIf_6_6 = new import16.NgIf(this._appEl_6.vcRef,this._TemplateRef_6_5);
    this._text_7 = this.renderer.createText(this._el_0,'\n        ',(null as any));
    this._expr_0 = import7.UNINITIALIZED;
    this._expr_1 = import7.UNINITIALIZED;
    this._expr_2 = import7.UNINITIALIZED;
    this.init([].concat([this._el_0]),[
      this._el_0,
      this._text_1,
      this._anchor_2,
      this._text_3,
      this._anchor_4,
      this._text_5,
      this._anchor_6,
      this._text_7
    ]
    ,[],[]);
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import18.TemplateRef) && (2 === requestNodeIndex))) { return this._TemplateRef_2_5; }
    if (((token === import16.NgIf) && (2 === requestNodeIndex))) { return this._NgIf_2_6; }
    if (((token === import18.TemplateRef) && (4 === requestNodeIndex))) { return this._TemplateRef_4_5; }
    if (((token === import16.NgIf) && (4 === requestNodeIndex))) { return this._NgIf_4_6; }
    if (((token === import18.TemplateRef) && (6 === requestNodeIndex))) { return this._TemplateRef_6_5; }
    if (((token === import16.NgIf) && (6 === requestNodeIndex))) { return this._NgIf_6_6; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    const currVal_0:any = this.parent.context.form.get('username').errors.required;
    if (import4.checkBinding(throwOnChange,this._expr_0,currVal_0)) {
      this._NgIf_2_6.ngIf = currVal_0;
      this._expr_0 = currVal_0;
    }
    const currVal_1:any = this.parent.context.form.get('username').errors.shouldBeUnique;
    if (import4.checkBinding(throwOnChange,this._expr_1,currVal_1)) {
      this._NgIf_4_6.ngIf = currVal_1;
      this._expr_1 = currVal_1;
    }
    const currVal_2:any = this.parent.context.form.get('username').errors.cannotContainSpace;
    if (import4.checkBinding(throwOnChange,this._expr_2,currVal_2)) {
      this._NgIf_6_6.ngIf = currVal_2;
      this._expr_2 = currVal_2;
    }
    this.detectContentChildrenChanges(throwOnChange);
    this.detectViewChildrenChanges(throwOnChange);
  }
}
function viewFactory_SignUpFormComponent2(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement):import1.AppView<any> {
  return new _View_SignUpFormComponent2(viewUtils,parentInjector,declarationEl);
}
class _View_SignUpFormComponent3 extends import1.AppView<any> {
  _el_0:any;
  _text_1:any;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement) {
    super(_View_SignUpFormComponent3,renderType_SignUpFormComponent,import6.ViewType.EMBEDDED,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import2.AppElement {
    this._el_0 = this.renderer.createElement((null as any),'div',(null as any));
    this.renderer.setElementAttribute(this._el_0,'class','alert alert-danger');
    this._text_1 = this.renderer.createText(this._el_0,'Username is required.',(null as any));
    this.init([].concat([this._el_0]),[
      this._el_0,
      this._text_1
    ]
    ,[],[]);
    return (null as any);
  }
}
function viewFactory_SignUpFormComponent3(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement):import1.AppView<any> {
  return new _View_SignUpFormComponent3(viewUtils,parentInjector,declarationEl);
}
class _View_SignUpFormComponent4 extends import1.AppView<any> {
  _el_0:any;
  _text_1:any;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement) {
    super(_View_SignUpFormComponent4,renderType_SignUpFormComponent,import6.ViewType.EMBEDDED,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import2.AppElement {
    this._el_0 = this.renderer.createElement((null as any),'div',(null as any));
    this.renderer.setElementAttribute(this._el_0,'class','div alert alert-danger');
    this._text_1 = this.renderer.createText(this._el_0,'This Username is already taken.',(null as any));
    this.init([].concat([this._el_0]),[
      this._el_0,
      this._text_1
    ]
    ,[],[]);
    return (null as any);
  }
}
function viewFactory_SignUpFormComponent4(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement):import1.AppView<any> {
  return new _View_SignUpFormComponent4(viewUtils,parentInjector,declarationEl);
}
class _View_SignUpFormComponent5 extends import1.AppView<any> {
  _el_0:any;
  _text_1:any;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement) {
    super(_View_SignUpFormComponent5,renderType_SignUpFormComponent,import6.ViewType.EMBEDDED,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import2.AppElement {
    this._el_0 = this.renderer.createElement((null as any),'div',(null as any));
    this.renderer.setElementAttribute(this._el_0,'class','div alert alert-danger');
    this._text_1 = this.renderer.createText(this._el_0,'Username cannot contain spaces.',(null as any));
    this.init([].concat([this._el_0]),[
      this._el_0,
      this._text_1
    ]
    ,[],[]);
    return (null as any);
  }
}
function viewFactory_SignUpFormComponent5(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement):import1.AppView<any> {
  return new _View_SignUpFormComponent5(viewUtils,parentInjector,declarationEl);
}
class _View_SignUpFormComponent6 extends import1.AppView<any> {
  _el_0:any;
  _text_1:any;
  _anchor_2:any;
  /*private*/ _appEl_2:import2.AppElement;
  _TemplateRef_2_5:any;
  _NgIf_2_6:import16.NgIf;
  _text_3:any;
  _anchor_4:any;
  /*private*/ _appEl_4:import2.AppElement;
  _TemplateRef_4_5:any;
  _NgIf_4_6:import16.NgIf;
  _text_5:any;
  /*private*/ _expr_0:any;
  /*private*/ _expr_1:any;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement) {
    super(_View_SignUpFormComponent6,renderType_SignUpFormComponent,import6.ViewType.EMBEDDED,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import2.AppElement {
    this._el_0 = this.renderer.createElement((null as any),'div',(null as any));
    this._text_1 = this.renderer.createText(this._el_0,'\n            ',(null as any));
    this._anchor_2 = this.renderer.createTemplateAnchor(this._el_0,(null as any));
    this._appEl_2 = new import2.AppElement(2,0,this,this._anchor_2);
    this._TemplateRef_2_5 = new import18.TemplateRef_(this._appEl_2,viewFactory_SignUpFormComponent7);
    this._NgIf_2_6 = new import16.NgIf(this._appEl_2.vcRef,this._TemplateRef_2_5);
    this._text_3 = this.renderer.createText(this._el_0,'\n            ',(null as any));
    this._anchor_4 = this.renderer.createTemplateAnchor(this._el_0,(null as any));
    this._appEl_4 = new import2.AppElement(4,0,this,this._anchor_4);
    this._TemplateRef_4_5 = new import18.TemplateRef_(this._appEl_4,viewFactory_SignUpFormComponent8);
    this._NgIf_4_6 = new import16.NgIf(this._appEl_4.vcRef,this._TemplateRef_4_5);
    this._text_5 = this.renderer.createText(this._el_0,'\n        ',(null as any));
    this._expr_0 = import7.UNINITIALIZED;
    this._expr_1 = import7.UNINITIALIZED;
    this.init([].concat([this._el_0]),[
      this._el_0,
      this._text_1,
      this._anchor_2,
      this._text_3,
      this._anchor_4,
      this._text_5
    ]
    ,[],[]);
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import18.TemplateRef) && (2 === requestNodeIndex))) { return this._TemplateRef_2_5; }
    if (((token === import16.NgIf) && (2 === requestNodeIndex))) { return this._NgIf_2_6; }
    if (((token === import18.TemplateRef) && (4 === requestNodeIndex))) { return this._TemplateRef_4_5; }
    if (((token === import16.NgIf) && (4 === requestNodeIndex))) { return this._NgIf_4_6; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    const currVal_0:any = this.parent.context.form.get('email').errors.required;
    if (import4.checkBinding(throwOnChange,this._expr_0,currVal_0)) {
      this._NgIf_2_6.ngIf = currVal_0;
      this._expr_0 = currVal_0;
    }
    const currVal_1:any = this.parent.context.form.get('email').errors.shouldBeUnique;
    if (import4.checkBinding(throwOnChange,this._expr_1,currVal_1)) {
      this._NgIf_4_6.ngIf = currVal_1;
      this._expr_1 = currVal_1;
    }
    this.detectContentChildrenChanges(throwOnChange);
    this.detectViewChildrenChanges(throwOnChange);
  }
}
function viewFactory_SignUpFormComponent6(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement):import1.AppView<any> {
  return new _View_SignUpFormComponent6(viewUtils,parentInjector,declarationEl);
}
class _View_SignUpFormComponent7 extends import1.AppView<any> {
  _el_0:any;
  _text_1:any;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement) {
    super(_View_SignUpFormComponent7,renderType_SignUpFormComponent,import6.ViewType.EMBEDDED,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import2.AppElement {
    this._el_0 = this.renderer.createElement((null as any),'div',(null as any));
    this.renderer.setElementAttribute(this._el_0,'class','alert alert-danger');
    this._text_1 = this.renderer.createText(this._el_0,'Email is required.',(null as any));
    this.init([].concat([this._el_0]),[
      this._el_0,
      this._text_1
    ]
    ,[],[]);
    return (null as any);
  }
}
function viewFactory_SignUpFormComponent7(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement):import1.AppView<any> {
  return new _View_SignUpFormComponent7(viewUtils,parentInjector,declarationEl);
}
class _View_SignUpFormComponent8 extends import1.AppView<any> {
  _el_0:any;
  _text_1:any;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement) {
    super(_View_SignUpFormComponent8,renderType_SignUpFormComponent,import6.ViewType.EMBEDDED,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import2.AppElement {
    this._el_0 = this.renderer.createElement((null as any),'div',(null as any));
    this.renderer.setElementAttribute(this._el_0,'class','div alert alert-danger');
    this._text_1 = this.renderer.createText(this._el_0,'This Email is already taken.',(null as any));
    this.init([].concat([this._el_0]),[
      this._el_0,
      this._text_1
    ]
    ,[],[]);
    return (null as any);
  }
}
function viewFactory_SignUpFormComponent8(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement):import1.AppView<any> {
  return new _View_SignUpFormComponent8(viewUtils,parentInjector,declarationEl);
}
class _View_SignUpFormComponent9 extends import1.AppView<any> {
  _el_0:any;
  _text_1:any;
  _anchor_2:any;
  /*private*/ _appEl_2:import2.AppElement;
  _TemplateRef_2_5:any;
  _NgIf_2_6:import16.NgIf;
  _text_3:any;
  _anchor_4:any;
  /*private*/ _appEl_4:import2.AppElement;
  _TemplateRef_4_5:any;
  _NgIf_4_6:import16.NgIf;
  _text_5:any;
  /*private*/ _expr_0:any;
  /*private*/ _expr_1:any;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement) {
    super(_View_SignUpFormComponent9,renderType_SignUpFormComponent,import6.ViewType.EMBEDDED,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import2.AppElement {
    this._el_0 = this.renderer.createElement((null as any),'div',(null as any));
    this._text_1 = this.renderer.createText(this._el_0,'\n            ',(null as any));
    this._anchor_2 = this.renderer.createTemplateAnchor(this._el_0,(null as any));
    this._appEl_2 = new import2.AppElement(2,0,this,this._anchor_2);
    this._TemplateRef_2_5 = new import18.TemplateRef_(this._appEl_2,viewFactory_SignUpFormComponent10);
    this._NgIf_2_6 = new import16.NgIf(this._appEl_2.vcRef,this._TemplateRef_2_5);
    this._text_3 = this.renderer.createText(this._el_0,'\n            ',(null as any));
    this._anchor_4 = this.renderer.createTemplateAnchor(this._el_0,(null as any));
    this._appEl_4 = new import2.AppElement(4,0,this,this._anchor_4);
    this._TemplateRef_4_5 = new import18.TemplateRef_(this._appEl_4,viewFactory_SignUpFormComponent11);
    this._NgIf_4_6 = new import16.NgIf(this._appEl_4.vcRef,this._TemplateRef_4_5);
    this._text_5 = this.renderer.createText(this._el_0,'\n        ',(null as any));
    this._expr_0 = import7.UNINITIALIZED;
    this._expr_1 = import7.UNINITIALIZED;
    this.init([].concat([this._el_0]),[
      this._el_0,
      this._text_1,
      this._anchor_2,
      this._text_3,
      this._anchor_4,
      this._text_5
    ]
    ,[],[]);
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import18.TemplateRef) && (2 === requestNodeIndex))) { return this._TemplateRef_2_5; }
    if (((token === import16.NgIf) && (2 === requestNodeIndex))) { return this._NgIf_2_6; }
    if (((token === import18.TemplateRef) && (4 === requestNodeIndex))) { return this._TemplateRef_4_5; }
    if (((token === import16.NgIf) && (4 === requestNodeIndex))) { return this._NgIf_4_6; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    const currVal_0:any = this.parent.context.form.get('password').errors.required;
    if (import4.checkBinding(throwOnChange,this._expr_0,currVal_0)) {
      this._NgIf_2_6.ngIf = currVal_0;
      this._expr_0 = currVal_0;
    }
    const currVal_1:any = this.parent.context.form.get('password').errors.complexPassword;
    if (import4.checkBinding(throwOnChange,this._expr_1,currVal_1)) {
      this._NgIf_4_6.ngIf = currVal_1;
      this._expr_1 = currVal_1;
    }
    this.detectContentChildrenChanges(throwOnChange);
    this.detectViewChildrenChanges(throwOnChange);
  }
}
function viewFactory_SignUpFormComponent9(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement):import1.AppView<any> {
  return new _View_SignUpFormComponent9(viewUtils,parentInjector,declarationEl);
}
class _View_SignUpFormComponent10 extends import1.AppView<any> {
  _el_0:any;
  _text_1:any;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement) {
    super(_View_SignUpFormComponent10,renderType_SignUpFormComponent,import6.ViewType.EMBEDDED,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import2.AppElement {
    this._el_0 = this.renderer.createElement((null as any),'div',(null as any));
    this.renderer.setElementAttribute(this._el_0,'class','alert alert-danger');
    this._text_1 = this.renderer.createText(this._el_0,'Password is required.',(null as any));
    this.init([].concat([this._el_0]),[
      this._el_0,
      this._text_1
    ]
    ,[],[]);
    return (null as any);
  }
}
function viewFactory_SignUpFormComponent10(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement):import1.AppView<any> {
  return new _View_SignUpFormComponent10(viewUtils,parentInjector,declarationEl);
}
class _View_SignUpFormComponent11 extends import1.AppView<any> {
  _el_0:any;
  _text_1:any;
  /*private*/ _expr_0:any;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement) {
    super(_View_SignUpFormComponent11,renderType_SignUpFormComponent,import6.ViewType.EMBEDDED,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import2.AppElement {
    this._el_0 = this.renderer.createElement((null as any),'div',(null as any));
    this.renderer.setElementAttribute(this._el_0,'class','alert alert-danger');
    this._text_1 = this.renderer.createText(this._el_0,'',(null as any));
    this._expr_0 = import7.UNINITIALIZED;
    this.init([].concat([this._el_0]),[
      this._el_0,
      this._text_1
    ]
    ,[],[]);
    return (null as any);
  }
  detectChangesInternal(throwOnChange:boolean):void {
    this.detectContentChildrenChanges(throwOnChange);
    const currVal_0:any = import4.interpolate(1,'\n                Password should be minimum ',this.parent.parent.context.form.get('password').errors.complexPassword.minLength,' characters.');
    if (import4.checkBinding(throwOnChange,this._expr_0,currVal_0)) {
      this.renderer.setText(this._text_1,currVal_0);
      this._expr_0 = currVal_0;
    }
    this.detectViewChildrenChanges(throwOnChange);
  }
}
function viewFactory_SignUpFormComponent11(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement):import1.AppView<any> {
  return new _View_SignUpFormComponent11(viewUtils,parentInjector,declarationEl);
}
class _View_SignUpFormComponent12 extends import1.AppView<any> {
  _el_0:any;
  _text_1:any;
  _anchor_2:any;
  /*private*/ _appEl_2:import2.AppElement;
  _TemplateRef_2_5:any;
  _NgIf_2_6:import16.NgIf;
  _text_3:any;
  /*private*/ _expr_0:any;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement) {
    super(_View_SignUpFormComponent12,renderType_SignUpFormComponent,import6.ViewType.EMBEDDED,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import2.AppElement {
    this._el_0 = this.renderer.createElement((null as any),'div',(null as any));
    this._text_1 = this.renderer.createText(this._el_0,'\n            ',(null as any));
    this._anchor_2 = this.renderer.createTemplateAnchor(this._el_0,(null as any));
    this._appEl_2 = new import2.AppElement(2,0,this,this._anchor_2);
    this._TemplateRef_2_5 = new import18.TemplateRef_(this._appEl_2,viewFactory_SignUpFormComponent13);
    this._NgIf_2_6 = new import16.NgIf(this._appEl_2.vcRef,this._TemplateRef_2_5);
    this._text_3 = this.renderer.createText(this._el_0,'\n        ',(null as any));
    this._expr_0 = import7.UNINITIALIZED;
    this.init([].concat([this._el_0]),[
      this._el_0,
      this._text_1,
      this._anchor_2,
      this._text_3
    ]
    ,[],[]);
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import18.TemplateRef) && (2 === requestNodeIndex))) { return this._TemplateRef_2_5; }
    if (((token === import16.NgIf) && (2 === requestNodeIndex))) { return this._NgIf_2_6; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    const currVal_0:any = this.parent.context.form.get('confirmPassword').errors.required;
    if (import4.checkBinding(throwOnChange,this._expr_0,currVal_0)) {
      this._NgIf_2_6.ngIf = currVal_0;
      this._expr_0 = currVal_0;
    }
    this.detectContentChildrenChanges(throwOnChange);
    this.detectViewChildrenChanges(throwOnChange);
  }
}
function viewFactory_SignUpFormComponent12(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement):import1.AppView<any> {
  return new _View_SignUpFormComponent12(viewUtils,parentInjector,declarationEl);
}
class _View_SignUpFormComponent13 extends import1.AppView<any> {
  _el_0:any;
  _text_1:any;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement) {
    super(_View_SignUpFormComponent13,renderType_SignUpFormComponent,import6.ViewType.EMBEDDED,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import2.AppElement {
    this._el_0 = this.renderer.createElement((null as any),'div',(null as any));
    this.renderer.setElementAttribute(this._el_0,'class','alert alert-danger');
    this._text_1 = this.renderer.createText(this._el_0,'Confirm the password.',(null as any));
    this.init([].concat([this._el_0]),[
      this._el_0,
      this._text_1
    ]
    ,[],[]);
    return (null as any);
  }
}
function viewFactory_SignUpFormComponent13(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement):import1.AppView<any> {
  return new _View_SignUpFormComponent13(viewUtils,parentInjector,declarationEl);
}
class _View_SignUpFormComponent14 extends import1.AppView<any> {
  _el_0:any;
  _text_1:any;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement) {
    super(_View_SignUpFormComponent14,renderType_SignUpFormComponent,import6.ViewType.EMBEDDED,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import2.AppElement {
    this._el_0 = this.renderer.createElement((null as any),'div',(null as any));
    this.renderer.setElementAttribute(this._el_0,'class','alert alert-danger');
    this._text_1 = this.renderer.createText(this._el_0,'Passwords don\'t match.',(null as any));
    this.init([].concat([this._el_0]),[
      this._el_0,
      this._text_1
    ]
    ,[],[]);
    return (null as any);
  }
}
function viewFactory_SignUpFormComponent14(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement):import1.AppView<any> {
  return new _View_SignUpFormComponent14(viewUtils,parentInjector,declarationEl);
}