/**
 * This file is generated by the Angular 2 template compiler.
 * Do not edit.
 */
 /* tslint:disable */

import * as import0 from '@angular/core/src/render/api';
import * as import1 from '@angular/core/src/linker/view';
import * as import2 from '@angular/core/src/linker/element';
import * as import3 from './header.component';
import * as import4 from '@angular/core/src/linker/view_utils';
import * as import5 from '@angular/core/src/di/injector';
import * as import6 from '@angular/core/src/linker/view_type';
import * as import7 from '@angular/core/src/change_detection/change_detection';
import * as import8 from '@angular/router/src/router';
import * as import9 from './auth/auth.service';
import * as import10 from '@angular/core/src/metadata/view';
import * as import11 from '@angular/core/src/linker/component_factory';
import * as import12 from './header.component.css.shim';
import * as import13 from '@angular/router/src/directives/router_link';
import * as import14 from '@angular/router/src/directives/router_link_active';
import * as import15 from '@angular/core/src/linker/query_list';
import * as import16 from '@angular/common/src/directives/ng_if';
import * as import17 from '@angular/router/src/router_state';
import * as import18 from '@angular/common/src/location/location_strategy';
import * as import19 from '@angular/core/src/linker/element_ref';
import * as import20 from '@angular/core/src/linker/template_ref';
import * as import21 from '@angular/core/src/security';
var renderType_HeaderComponent_Host:import0.RenderComponentType = (null as any);
class _View_HeaderComponent_Host0 extends import1.AppView<any> {
  _el_0:any;
  /*private*/ _appEl_0:import2.AppElement;
  _HeaderComponent_0_4:import3.HeaderComponent;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement) {
    super(_View_HeaderComponent_Host0,renderType_HeaderComponent_Host,import6.ViewType.HOST,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import2.AppElement {
    this._el_0 = this.selectOrCreateHostElement('app-header',rootSelector,(null as any));
    this._appEl_0 = new import2.AppElement(0,(null as any),this,this._el_0);
    var compView_0:any = viewFactory_HeaderComponent0(this.viewUtils,this.injector(0),this._appEl_0);
    this._HeaderComponent_0_4 = new import3.HeaderComponent(this.parentInjector.get(import8.Router),this.parentInjector.get(import9.AuthService));
    this._appEl_0.initComponent(this._HeaderComponent_0_4,[],compView_0);
    compView_0.create(this._HeaderComponent_0_4,this.projectableNodes,(null as any));
    this.init([].concat([this._el_0]),[this._el_0],[],[]);
    return this._appEl_0;
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import3.HeaderComponent) && (0 === requestNodeIndex))) { return this._HeaderComponent_0_4; }
    return notFoundResult;
  }
}
function viewFactory_HeaderComponent_Host0(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement):import1.AppView<any> {
  if ((renderType_HeaderComponent_Host === (null as any))) { (renderType_HeaderComponent_Host = viewUtils.createRenderComponentType('',0,import10.ViewEncapsulation.None,[],{})); }
  return new _View_HeaderComponent_Host0(viewUtils,parentInjector,declarationEl);
}
export const HeaderComponentNgFactory:import11.ComponentFactory<import3.HeaderComponent> = new import11.ComponentFactory<import3.HeaderComponent>('app-header',viewFactory_HeaderComponent_Host0,import3.HeaderComponent);
const styles_HeaderComponent:any[] = [import12.styles];
var renderType_HeaderComponent:import0.RenderComponentType = (null as any);
class _View_HeaderComponent0 extends import1.AppView<import3.HeaderComponent> {
  _el_0:any;
  _text_1:any;
  _el_2:any;
  _text_3:any;
  _text_4:any;
  _el_5:any;
  _text_6:any;
  _el_7:any;
  _text_8:any;
  _el_9:any;
  _text_10:any;
  _text_11:any;
  _el_12:any;
  _text_13:any;
  _el_14:any;
  _text_15:any;
  _el_16:any;
  _text_17:any;
  _text_18:any;
  _el_19:any;
  _RouterLinkWithHref_19_3:import13.RouterLinkWithHref;
  _text_20:any;
  _text_21:any;
  _text_22:any;
  _text_23:any;
  _el_24:any;
  _text_25:any;
  _el_26:any;
  _text_27:any;
  _el_28:any;
  _RouterLinkActive_28_3:import14.RouterLinkActive;
  _query_RouterLink_28_0:import15.QueryList<any>;
  _query_RouterLinkWithHref_28_1:import15.QueryList<any>;
  _el_29:any;
  _RouterLinkWithHref_29_3:import13.RouterLinkWithHref;
  _text_30:any;
  _text_31:any;
  _text_32:any;
  _el_33:any;
  _text_34:any;
  _el_35:any;
  _text_36:any;
  _el_37:any;
  _text_38:any;
  _el_39:any;
  _text_40:any;
  _el_41:any;
  _el_42:any;
  _RouterLinkWithHref_42_3:import13.RouterLinkWithHref;
  _text_43:any;
  _text_44:any;
  _text_45:any;
  _text_46:any;
  _text_47:any;
  _el_48:any;
  _text_49:any;
  _el_50:any;
  _text_51:any;
  _el_52:any;
  _text_53:any;
  _el_54:any;
  _text_55:any;
  _el_56:any;
  _el_57:any;
  _text_58:any;
  _text_59:any;
  _el_60:any;
  _el_61:any;
  _text_62:any;
  _text_63:any;
  _el_64:any;
  _el_65:any;
  _text_66:any;
  _text_67:any;
  _el_68:any;
  _el_69:any;
  _text_70:any;
  _text_71:any;
  _el_72:any;
  _el_73:any;
  _text_74:any;
  _text_75:any;
  _el_76:any;
  _el_77:any;
  _text_78:any;
  _text_79:any;
  _text_80:any;
  _text_81:any;
  _text_82:any;
  _text_83:any;
  _el_84:any;
  _text_85:any;
  _anchor_86:any;
  /*private*/ _appEl_86:import2.AppElement;
  _TemplateRef_86_5:any;
  _NgIf_86_6:import16.NgIf;
  _text_87:any;
  _anchor_88:any;
  /*private*/ _appEl_88:import2.AppElement;
  _TemplateRef_88_5:any;
  _NgIf_88_6:import16.NgIf;
  _text_89:any;
  _anchor_90:any;
  /*private*/ _appEl_90:import2.AppElement;
  _TemplateRef_90_5:any;
  _NgIf_90_6:import16.NgIf;
  _text_91:any;
  _text_92:any;
  _text_93:any;
  _text_94:any;
  _text_95:any;
  /*private*/ _expr_1:any;
  /*private*/ _expr_2:any;
  /*private*/ _expr_3:any;
  /*private*/ _expr_5:any;
  /*private*/ _expr_6:any;
  /*private*/ _expr_8:any;
  /*private*/ _expr_9:any;
  /*private*/ _expr_10:any;
  /*private*/ _expr_11:any;
  /*private*/ _expr_12:any;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement) {
    super(_View_HeaderComponent0,renderType_HeaderComponent,import6.ViewType.COMPONENT,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import2.AppElement {
    const parentRenderNode:any = this.renderer.createViewRoot(this.declarationAppElement.nativeElement);
    this._el_0 = this.renderer.createElement(parentRenderNode,'nav',(null as any));
    this.renderer.setElementAttribute(this._el_0,'class','navbar');
    this._text_1 = this.renderer.createText(this._el_0,'\n  ',(null as any));
    this._el_2 = this.renderer.createElement(this._el_0,'div',(null as any));
    this.renderer.setElementAttribute(this._el_2,'class','container-fluid');
    this._text_3 = this.renderer.createText(this._el_2,'\n    ',(null as any));
    this._text_4 = this.renderer.createText(this._el_2,'\n    ',(null as any));
    this._el_5 = this.renderer.createElement(this._el_2,'div',(null as any));
    this.renderer.setElementAttribute(this._el_5,'class','navbar-header');
    this._text_6 = this.renderer.createText(this._el_5,'\n      ',(null as any));
    this._el_7 = this.renderer.createElement(this._el_5,'button',(null as any));
    this.renderer.setElementAttribute(this._el_7,'aria-expanded','false');
    this.renderer.setElementAttribute(this._el_7,'class','navbar-toggle collapsed');
    this.renderer.setElementAttribute(this._el_7,'data-target','#bs-example-navbar-collapse-1');
    this.renderer.setElementAttribute(this._el_7,'data-toggle','collapse');
    this.renderer.setElementAttribute(this._el_7,'type','button');
    this._text_8 = this.renderer.createText(this._el_7,'\n        ',(null as any));
    this._el_9 = this.renderer.createElement(this._el_7,'span',(null as any));
    this.renderer.setElementAttribute(this._el_9,'class','sr-only');
    this._text_10 = this.renderer.createText(this._el_9,'Toggle navigation',(null as any));
    this._text_11 = this.renderer.createText(this._el_7,'\n        ',(null as any));
    this._el_12 = this.renderer.createElement(this._el_7,'span',(null as any));
    this.renderer.setElementAttribute(this._el_12,'class','icon-bar');
    this._text_13 = this.renderer.createText(this._el_7,'\n        ',(null as any));
    this._el_14 = this.renderer.createElement(this._el_7,'span',(null as any));
    this.renderer.setElementAttribute(this._el_14,'class','icon-bar');
    this._text_15 = this.renderer.createText(this._el_7,'\n        ',(null as any));
    this._el_16 = this.renderer.createElement(this._el_7,'span',(null as any));
    this.renderer.setElementAttribute(this._el_16,'class','icon-bar');
    this._text_17 = this.renderer.createText(this._el_7,'\n      ',(null as any));
    this._text_18 = this.renderer.createText(this._el_5,'\n      ',(null as any));
    this._el_19 = this.renderer.createElement(this._el_5,'a',(null as any));
    this.renderer.setElementAttribute(this._el_19,'class','navbar-brand');
    this.renderer.setElementAttribute(this._el_19,'routerLink','');
    this._RouterLinkWithHref_19_3 = new import13.RouterLinkWithHref(this.parentInjector.get(import8.Router),this.parentInjector.get(import17.ActivatedRoute),this.parentInjector.get(import18.LocationStrategy));
    this._text_20 = this.renderer.createText(this._el_19,'Unity Study Group',(null as any));
    this._text_21 = this.renderer.createText(this._el_5,'\n    ',(null as any));
    this._text_22 = this.renderer.createText(this._el_2,'\n\n    ',(null as any));
    this._text_23 = this.renderer.createText(this._el_2,'\n    ',(null as any));
    this._el_24 = this.renderer.createElement(this._el_2,'div',(null as any));
    this.renderer.setElementAttribute(this._el_24,'class','collapse navbar-collapse');
    this.renderer.setElementAttribute(this._el_24,'id','bs-example-navbar-collapse-1');
    this._text_25 = this.renderer.createText(this._el_24,'\n      ',(null as any));
    this._el_26 = this.renderer.createElement(this._el_24,'ul',(null as any));
    this.renderer.setElementAttribute(this._el_26,'class','nav navbar-nav');
    this._text_27 = this.renderer.createText(this._el_26,'\n        ',(null as any));
    this._el_28 = this.renderer.createElement(this._el_26,'li',(null as any));
    this.renderer.setElementAttribute(this._el_28,'routerLinkActive','active');
    this._RouterLinkActive_28_3 = new import14.RouterLinkActive(this.parentInjector.get(import8.Router),new import19.ElementRef(this._el_28),this.renderer);
    this._query_RouterLink_28_0 = new import15.QueryList<any>();
    this._query_RouterLinkWithHref_28_1 = new import15.QueryList<any>();
    this._el_29 = this.renderer.createElement(this._el_28,'a',(null as any));
    this.renderer.setElementAttribute(this._el_29,'routerLink','news');
    this._RouterLinkWithHref_29_3 = new import13.RouterLinkWithHref(this.parentInjector.get(import8.Router),this.parentInjector.get(import17.ActivatedRoute),this.parentInjector.get(import18.LocationStrategy));
    this._text_30 = this.renderer.createText(this._el_29,'News',(null as any));
    this._text_31 = this.renderer.createText(this._el_26,'\n        ',(null as any));
    this._text_32 = this.renderer.createText(this._el_26,'\n        ',(null as any));
    this._el_33 = this.renderer.createElement(this._el_26,'li',(null as any));
    this.renderer.setElementAttribute(this._el_33,'class','dropdown');
    this._text_34 = this.renderer.createText(this._el_33,'\n          ',(null as any));
    this._el_35 = this.renderer.createElement(this._el_33,'a',(null as any));
    this.renderer.setElementAttribute(this._el_35,'aria-expanded','false');
    this.renderer.setElementAttribute(this._el_35,'aria-haspopup','true');
    this.renderer.setElementAttribute(this._el_35,'class','dropdown-toggle');
    this.renderer.setElementAttribute(this._el_35,'data-toggle','dropdown');
    this.renderer.setElementAttribute(this._el_35,'href','#');
    this.renderer.setElementAttribute(this._el_35,'role','button');
    this._text_36 = this.renderer.createText(this._el_35,'Resources ',(null as any));
    this._el_37 = this.renderer.createElement(this._el_35,'span',(null as any));
    this.renderer.setElementAttribute(this._el_37,'class','caret');
    this._text_38 = this.renderer.createText(this._el_33,'\n          ',(null as any));
    this._el_39 = this.renderer.createElement(this._el_33,'ul',(null as any));
    this.renderer.setElementAttribute(this._el_39,'class','dropdown-menu');
    this._text_40 = this.renderer.createText(this._el_39,'\n            ',(null as any));
    this._el_41 = this.renderer.createElement(this._el_39,'li',(null as any));
    this._el_42 = this.renderer.createElement(this._el_41,'a',(null as any));
    this.renderer.setElementAttribute(this._el_42,'routerLink','collisiontable');
    this._RouterLinkWithHref_42_3 = new import13.RouterLinkWithHref(this.parentInjector.get(import8.Router),this.parentInjector.get(import17.ActivatedRoute),this.parentInjector.get(import18.LocationStrategy));
    this._text_43 = this.renderer.createText(this._el_42,'Collision Table',(null as any));
    this._text_44 = this.renderer.createText(this._el_39,'\n            ',(null as any));
    this._text_45 = this.renderer.createText(this._el_39,'\n          ',(null as any));
    this._text_46 = this.renderer.createText(this._el_33,'\n          ',(null as any));
    this._text_47 = this.renderer.createText(this._el_26,'\n          ',(null as any));
    this._el_48 = this.renderer.createElement(this._el_26,'li',(null as any));
    this.renderer.setElementAttribute(this._el_48,'class','dropdown');
    this._text_49 = this.renderer.createText(this._el_48,'\n          ',(null as any));
    this._el_50 = this.renderer.createElement(this._el_48,'a',(null as any));
    this.renderer.setElementAttribute(this._el_50,'aria-expanded','false');
    this.renderer.setElementAttribute(this._el_50,'aria-haspopup','true');
    this.renderer.setElementAttribute(this._el_50,'class','dropdown-toggle');
    this.renderer.setElementAttribute(this._el_50,'data-toggle','dropdown');
    this.renderer.setElementAttribute(this._el_50,'href','#');
    this.renderer.setElementAttribute(this._el_50,'role','button');
    this._text_51 = this.renderer.createText(this._el_50,'Unity Official ',(null as any));
    this._el_52 = this.renderer.createElement(this._el_50,'span',(null as any));
    this.renderer.setElementAttribute(this._el_52,'class','caret');
    this._text_53 = this.renderer.createText(this._el_48,'\n          ',(null as any));
    this._el_54 = this.renderer.createElement(this._el_48,'ul',(null as any));
    this.renderer.setElementAttribute(this._el_54,'class','dropdown-menu');
    this._text_55 = this.renderer.createText(this._el_54,'\n            ',(null as any));
    this._el_56 = this.renderer.createElement(this._el_54,'li',(null as any));
    this._el_57 = this.renderer.createElement(this._el_56,'a',(null as any));
    this.renderer.setElementAttribute(this._el_57,'href','https://docs.unity3d.com/ScriptReference/');
    this._text_58 = this.renderer.createText(this._el_57,'Scripting API',(null as any));
    this._text_59 = this.renderer.createText(this._el_54,'\n            ',(null as any));
    this._el_60 = this.renderer.createElement(this._el_54,'li',(null as any));
    this._el_61 = this.renderer.createElement(this._el_60,'a',(null as any));
    this.renderer.setElementAttribute(this._el_61,'href','https://forum.unity3d.com/');
    this._text_62 = this.renderer.createText(this._el_61,'Forums',(null as any));
    this._text_63 = this.renderer.createText(this._el_54,'\n            ',(null as any));
    this._el_64 = this.renderer.createElement(this._el_54,'li',(null as any));
    this._el_65 = this.renderer.createElement(this._el_64,'a',(null as any));
    this.renderer.setElementAttribute(this._el_65,'href','http://wiki.unity3d.com/index.php/Main_Page');
    this._text_66 = this.renderer.createText(this._el_65,'Wiki',(null as any));
    this._text_67 = this.renderer.createText(this._el_54,'\n            ',(null as any));
    this._el_68 = this.renderer.createElement(this._el_54,'li',(null as any));
    this._el_69 = this.renderer.createElement(this._el_68,'a',(null as any));
    this.renderer.setElementAttribute(this._el_69,'href','https://www.youtube.com/user/Unity3D');
    this._text_70 = this.renderer.createText(this._el_69,'YouTube',(null as any));
    this._text_71 = this.renderer.createText(this._el_54,'\n            ',(null as any));
    this._el_72 = this.renderer.createElement(this._el_54,'li',(null as any));
    this._el_73 = this.renderer.createElement(this._el_72,'a',(null as any));
    this.renderer.setElementAttribute(this._el_73,'href','https://www.unity3d.com/learn');
    this._text_74 = this.renderer.createText(this._el_73,'Learn',(null as any));
    this._text_75 = this.renderer.createText(this._el_54,'\n            ',(null as any));
    this._el_76 = this.renderer.createElement(this._el_54,'li',(null as any));
    this._el_77 = this.renderer.createElement(this._el_76,'a',(null as any));
    this.renderer.setElementAttribute(this._el_77,'href','https://store.unity.com/front-page');
    this._text_78 = this.renderer.createText(this._el_77,'Get Unity',(null as any));
    this._text_79 = this.renderer.createText(this._el_54,'\n            ',(null as any));
    this._text_80 = this.renderer.createText(this._el_54,'\n          ',(null as any));
    this._text_81 = this.renderer.createText(this._el_48,'\n        ',(null as any));
    this._text_82 = this.renderer.createText(this._el_26,'\n        \n      ',(null as any));
    this._text_83 = this.renderer.createText(this._el_24,'\n      ',(null as any));
    this._el_84 = this.renderer.createElement(this._el_24,'ul',(null as any));
    this.renderer.setElementAttribute(this._el_84,'class','nav navbar-nav navbar-right');
    this._text_85 = this.renderer.createText(this._el_84,'\n        ',(null as any));
    this._anchor_86 = this.renderer.createTemplateAnchor(this._el_84,(null as any));
    this._appEl_86 = new import2.AppElement(86,84,this,this._anchor_86);
    this._TemplateRef_86_5 = new import20.TemplateRef_(this._appEl_86,viewFactory_HeaderComponent1);
    this._NgIf_86_6 = new import16.NgIf(this._appEl_86.vcRef,this._TemplateRef_86_5);
    this._text_87 = this.renderer.createText(this._el_84,'\n        ',(null as any));
    this._anchor_88 = this.renderer.createTemplateAnchor(this._el_84,(null as any));
    this._appEl_88 = new import2.AppElement(88,84,this,this._anchor_88);
    this._TemplateRef_88_5 = new import20.TemplateRef_(this._appEl_88,viewFactory_HeaderComponent2);
    this._NgIf_88_6 = new import16.NgIf(this._appEl_88.vcRef,this._TemplateRef_88_5);
    this._text_89 = this.renderer.createText(this._el_84,'\n        ',(null as any));
    this._anchor_90 = this.renderer.createTemplateAnchor(this._el_84,(null as any));
    this._appEl_90 = new import2.AppElement(90,84,this,this._anchor_90);
    this._TemplateRef_90_5 = new import20.TemplateRef_(this._appEl_90,viewFactory_HeaderComponent3);
    this._NgIf_90_6 = new import16.NgIf(this._appEl_90.vcRef,this._TemplateRef_90_5);
    this._text_91 = this.renderer.createText(this._el_84,'      \n      ',(null as any));
    this._text_92 = this.renderer.createText(this._el_24,'\n    ',(null as any));
    this._text_93 = this.renderer.createText(this._el_2,'\n  ',(null as any));
    this._text_94 = this.renderer.createText(this._el_0,'\n',(null as any));
    this._text_95 = this.renderer.createText(parentRenderNode,'\n',(null as any));
    var disposable_0:Function = this.renderer.listen(this._el_19,'click',this.eventHandler(this._handle_click_19_0.bind(this)));
    this._expr_1 = import7.UNINITIALIZED;
    this._expr_2 = import7.UNINITIALIZED;
    this._expr_3 = import7.UNINITIALIZED;
    var disposable_1:Function = this.renderer.listen(this._el_29,'click',this.eventHandler(this._handle_click_29_0.bind(this)));
    this._expr_5 = import7.UNINITIALIZED;
    this._expr_6 = import7.UNINITIALIZED;
    var disposable_2:Function = this.renderer.listen(this._el_42,'click',this.eventHandler(this._handle_click_42_0.bind(this)));
    this._expr_8 = import7.UNINITIALIZED;
    this._expr_9 = import7.UNINITIALIZED;
    this._expr_10 = import7.UNINITIALIZED;
    this._expr_11 = import7.UNINITIALIZED;
    this._expr_12 = import7.UNINITIALIZED;
    this.init([],[
      this._el_0,
      this._text_1,
      this._el_2,
      this._text_3,
      this._text_4,
      this._el_5,
      this._text_6,
      this._el_7,
      this._text_8,
      this._el_9,
      this._text_10,
      this._text_11,
      this._el_12,
      this._text_13,
      this._el_14,
      this._text_15,
      this._el_16,
      this._text_17,
      this._text_18,
      this._el_19,
      this._text_20,
      this._text_21,
      this._text_22,
      this._text_23,
      this._el_24,
      this._text_25,
      this._el_26,
      this._text_27,
      this._el_28,
      this._el_29,
      this._text_30,
      this._text_31,
      this._text_32,
      this._el_33,
      this._text_34,
      this._el_35,
      this._text_36,
      this._el_37,
      this._text_38,
      this._el_39,
      this._text_40,
      this._el_41,
      this._el_42,
      this._text_43,
      this._text_44,
      this._text_45,
      this._text_46,
      this._text_47,
      this._el_48,
      this._text_49,
      this._el_50,
      this._text_51,
      this._el_52,
      this._text_53,
      this._el_54,
      this._text_55,
      this._el_56,
      this._el_57,
      this._text_58,
      this._text_59,
      this._el_60,
      this._el_61,
      this._text_62,
      this._text_63,
      this._el_64,
      this._el_65,
      this._text_66,
      this._text_67,
      this._el_68,
      this._el_69,
      this._text_70,
      this._text_71,
      this._el_72,
      this._el_73,
      this._text_74,
      this._text_75,
      this._el_76,
      this._el_77,
      this._text_78,
      this._text_79,
      this._text_80,
      this._text_81,
      this._text_82,
      this._text_83,
      this._el_84,
      this._text_85,
      this._anchor_86,
      this._text_87,
      this._anchor_88,
      this._text_89,
      this._anchor_90,
      this._text_91,
      this._text_92,
      this._text_93,
      this._text_94,
      this._text_95
    ]
    ,[
      disposable_0,
      disposable_1,
      disposable_2
    ]
    ,[]);
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import13.RouterLinkWithHref) && ((19 <= requestNodeIndex) && (requestNodeIndex <= 20)))) { return this._RouterLinkWithHref_19_3; }
    if (((token === import13.RouterLinkWithHref) && ((29 <= requestNodeIndex) && (requestNodeIndex <= 30)))) { return this._RouterLinkWithHref_29_3; }
    if (((token === import14.RouterLinkActive) && ((28 <= requestNodeIndex) && (requestNodeIndex <= 30)))) { return this._RouterLinkActive_28_3; }
    if (((token === import13.RouterLinkWithHref) && ((42 <= requestNodeIndex) && (requestNodeIndex <= 43)))) { return this._RouterLinkWithHref_42_3; }
    if (((token === import20.TemplateRef) && (86 === requestNodeIndex))) { return this._TemplateRef_86_5; }
    if (((token === import16.NgIf) && (86 === requestNodeIndex))) { return this._NgIf_86_6; }
    if (((token === import20.TemplateRef) && (88 === requestNodeIndex))) { return this._TemplateRef_88_5; }
    if (((token === import16.NgIf) && (88 === requestNodeIndex))) { return this._NgIf_88_6; }
    if (((token === import20.TemplateRef) && (90 === requestNodeIndex))) { return this._TemplateRef_90_5; }
    if (((token === import16.NgIf) && (90 === requestNodeIndex))) { return this._NgIf_90_6; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    var changes:{[key: string]:import7.SimpleChange} = (null as any);
    changes = (null as any);
    const currVal_1:any = '';
    if (import4.checkBinding(throwOnChange,this._expr_1,currVal_1)) {
      this._RouterLinkWithHref_19_3.routerLink = currVal_1;
      if ((changes === (null as any))) { (changes = {}); }
      changes['routerLink'] = new import7.SimpleChange(this._expr_1,currVal_1);
      this._expr_1 = currVal_1;
    }
    if ((changes !== (null as any))) { this._RouterLinkWithHref_19_3.ngOnChanges(changes); }
    changes = (null as any);
    const currVal_3:any = 'active';
    if (import4.checkBinding(throwOnChange,this._expr_3,currVal_3)) {
      this._RouterLinkActive_28_3.routerLinkActive = currVal_3;
      if ((changes === (null as any))) { (changes = {}); }
      changes['routerLinkActive'] = new import7.SimpleChange(this._expr_3,currVal_3);
      this._expr_3 = currVal_3;
    }
    if ((changes !== (null as any))) { this._RouterLinkActive_28_3.ngOnChanges(changes); }
    changes = (null as any);
    const currVal_5:any = 'news';
    if (import4.checkBinding(throwOnChange,this._expr_5,currVal_5)) {
      this._RouterLinkWithHref_29_3.routerLink = currVal_5;
      if ((changes === (null as any))) { (changes = {}); }
      changes['routerLink'] = new import7.SimpleChange(this._expr_5,currVal_5);
      this._expr_5 = currVal_5;
    }
    if ((changes !== (null as any))) { this._RouterLinkWithHref_29_3.ngOnChanges(changes); }
    changes = (null as any);
    const currVal_8:any = 'collisiontable';
    if (import4.checkBinding(throwOnChange,this._expr_8,currVal_8)) {
      this._RouterLinkWithHref_42_3.routerLink = currVal_8;
      if ((changes === (null as any))) { (changes = {}); }
      changes['routerLink'] = new import7.SimpleChange(this._expr_8,currVal_8);
      this._expr_8 = currVal_8;
    }
    if ((changes !== (null as any))) { this._RouterLinkWithHref_42_3.ngOnChanges(changes); }
    const currVal_10:boolean = !this.context.isLoggedIn();
    if (import4.checkBinding(throwOnChange,this._expr_10,currVal_10)) {
      this._NgIf_86_6.ngIf = currVal_10;
      this._expr_10 = currVal_10;
    }
    const currVal_11:boolean = !this.context.isLoggedIn();
    if (import4.checkBinding(throwOnChange,this._expr_11,currVal_11)) {
      this._NgIf_88_6.ngIf = currVal_11;
      this._expr_11 = currVal_11;
    }
    const currVal_12:any = this.context.isLoggedIn();
    if (import4.checkBinding(throwOnChange,this._expr_12,currVal_12)) {
      this._NgIf_90_6.ngIf = currVal_12;
      this._expr_12 = currVal_12;
    }
    this.detectContentChildrenChanges(throwOnChange);
    if (!throwOnChange) {
      if (this._query_RouterLink_28_0.dirty) {
        this._query_RouterLink_28_0.reset([]);
        this._RouterLinkActive_28_3.links = this._query_RouterLink_28_0;
        this._query_RouterLink_28_0.notifyOnChanges();
      }
      if (this._query_RouterLinkWithHref_28_1.dirty) {
        this._query_RouterLinkWithHref_28_1.reset([this._RouterLinkWithHref_29_3]);
        this._RouterLinkActive_28_3.linksWithHrefs = this._query_RouterLinkWithHref_28_1;
        this._query_RouterLinkWithHref_28_1.notifyOnChanges();
      }
      if ((this.numberOfChecks === 0)) { this._RouterLinkActive_28_3.ngAfterContentInit(); }
    }
    const currVal_2:any = this._RouterLinkWithHref_19_3.href;
    if (import4.checkBinding(throwOnChange,this._expr_2,currVal_2)) {
      this.renderer.setElementProperty(this._el_19,'href',this.viewUtils.sanitizer.sanitize(import21.SecurityContext.URL,currVal_2));
      this._expr_2 = currVal_2;
    }
    const currVal_6:any = this._RouterLinkWithHref_29_3.href;
    if (import4.checkBinding(throwOnChange,this._expr_6,currVal_6)) {
      this.renderer.setElementProperty(this._el_29,'href',this.viewUtils.sanitizer.sanitize(import21.SecurityContext.URL,currVal_6));
      this._expr_6 = currVal_6;
    }
    const currVal_9:any = this._RouterLinkWithHref_42_3.href;
    if (import4.checkBinding(throwOnChange,this._expr_9,currVal_9)) {
      this.renderer.setElementProperty(this._el_42,'href',this.viewUtils.sanitizer.sanitize(import21.SecurityContext.URL,currVal_9));
      this._expr_9 = currVal_9;
    }
    this.detectViewChildrenChanges(throwOnChange);
  }
  destroyInternal():void {
    this._RouterLinkWithHref_19_3.ngOnDestroy();
    this._RouterLinkWithHref_29_3.ngOnDestroy();
    this._RouterLinkActive_28_3.ngOnDestroy();
    this._RouterLinkWithHref_42_3.ngOnDestroy();
  }
  private _handle_click_19_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this._RouterLinkWithHref_19_3.onClick($event.button,$event.ctrlKey,$event.metaKey)) !== false);
    return (true && pd_0);
  }
  private _handle_click_29_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this._RouterLinkWithHref_29_3.onClick($event.button,$event.ctrlKey,$event.metaKey)) !== false);
    return (true && pd_0);
  }
  private _handle_click_42_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this._RouterLinkWithHref_42_3.onClick($event.button,$event.ctrlKey,$event.metaKey)) !== false);
    return (true && pd_0);
  }
}
export function viewFactory_HeaderComponent0(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement):import1.AppView<import3.HeaderComponent> {
  if ((renderType_HeaderComponent === (null as any))) { (renderType_HeaderComponent = viewUtils.createRenderComponentType('C:/Users/ketha/Desktop/projects/web/unitystudygroup/assets/app/header.component.html',0,import10.ViewEncapsulation.Emulated,styles_HeaderComponent,{})); }
  return new _View_HeaderComponent0(viewUtils,parentInjector,declarationEl);
}
class _View_HeaderComponent1 extends import1.AppView<any> {
  _el_0:any;
  _RouterLinkActive_0_3:import14.RouterLinkActive;
  _query_RouterLink_0_0:import15.QueryList<any>;
  _query_RouterLinkWithHref_0_1:import15.QueryList<any>;
  _el_1:any;
  _RouterLinkWithHref_1_3:import13.RouterLinkWithHref;
  _text_2:any;
  /*private*/ _expr_0:any;
  _arr_0:any;
  /*private*/ _expr_2:any;
  /*private*/ _expr_3:any;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement) {
    super(_View_HeaderComponent1,renderType_HeaderComponent,import6.ViewType.EMBEDDED,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import2.AppElement {
    this._el_0 = this.renderer.createElement((null as any),'li',(null as any));
    this.renderer.setElementAttribute(this._el_0,'routerLinkActive','active');
    this._RouterLinkActive_0_3 = new import14.RouterLinkActive(this.parent.parentInjector.get(import8.Router),new import19.ElementRef(this._el_0),this.renderer);
    this._query_RouterLink_0_0 = new import15.QueryList<any>();
    this._query_RouterLinkWithHref_0_1 = new import15.QueryList<any>();
    this._el_1 = this.renderer.createElement(this._el_0,'a',(null as any));
    this._RouterLinkWithHref_1_3 = new import13.RouterLinkWithHref(this.parent.parentInjector.get(import8.Router),this.parent.parentInjector.get(import17.ActivatedRoute),this.parent.parentInjector.get(import18.LocationStrategy));
    this._text_2 = this.renderer.createText(this._el_1,'Signin',(null as any));
    this._expr_0 = import7.UNINITIALIZED;
    var disposable_0:Function = this.renderer.listen(this._el_1,'click',this.eventHandler(this._handle_click_1_0.bind(this)));
    this._arr_0 = import4.pureProxy1((p0:any):any[] => {
      return [p0];
    });
    this._expr_2 = import7.UNINITIALIZED;
    this._expr_3 = import7.UNINITIALIZED;
    this.init([].concat([this._el_0]),[
      this._el_0,
      this._el_1,
      this._text_2
    ]
    ,[disposable_0],[]);
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import13.RouterLinkWithHref) && ((1 <= requestNodeIndex) && (requestNodeIndex <= 2)))) { return this._RouterLinkWithHref_1_3; }
    if (((token === import14.RouterLinkActive) && ((0 <= requestNodeIndex) && (requestNodeIndex <= 2)))) { return this._RouterLinkActive_0_3; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    var changes:{[key: string]:import7.SimpleChange} = (null as any);
    changes = (null as any);
    const currVal_0:any = 'active';
    if (import4.checkBinding(throwOnChange,this._expr_0,currVal_0)) {
      this._RouterLinkActive_0_3.routerLinkActive = currVal_0;
      if ((changes === (null as any))) { (changes = {}); }
      changes['routerLinkActive'] = new import7.SimpleChange(this._expr_0,currVal_0);
      this._expr_0 = currVal_0;
    }
    if ((changes !== (null as any))) { this._RouterLinkActive_0_3.ngOnChanges(changes); }
    changes = (null as any);
    const currVal_2:any = this._arr_0('login');
    if (import4.checkBinding(throwOnChange,this._expr_2,currVal_2)) {
      this._RouterLinkWithHref_1_3.routerLink = currVal_2;
      if ((changes === (null as any))) { (changes = {}); }
      changes['routerLink'] = new import7.SimpleChange(this._expr_2,currVal_2);
      this._expr_2 = currVal_2;
    }
    if ((changes !== (null as any))) { this._RouterLinkWithHref_1_3.ngOnChanges(changes); }
    this.detectContentChildrenChanges(throwOnChange);
    if (!throwOnChange) {
      if (this._query_RouterLink_0_0.dirty) {
        this._query_RouterLink_0_0.reset([]);
        this._RouterLinkActive_0_3.links = this._query_RouterLink_0_0;
        this._query_RouterLink_0_0.notifyOnChanges();
      }
      if (this._query_RouterLinkWithHref_0_1.dirty) {
        this._query_RouterLinkWithHref_0_1.reset([this._RouterLinkWithHref_1_3]);
        this._RouterLinkActive_0_3.linksWithHrefs = this._query_RouterLinkWithHref_0_1;
        this._query_RouterLinkWithHref_0_1.notifyOnChanges();
      }
      if ((this.numberOfChecks === 0)) { this._RouterLinkActive_0_3.ngAfterContentInit(); }
    }
    const currVal_3:any = this._RouterLinkWithHref_1_3.href;
    if (import4.checkBinding(throwOnChange,this._expr_3,currVal_3)) {
      this.renderer.setElementProperty(this._el_1,'href',this.viewUtils.sanitizer.sanitize(import21.SecurityContext.URL,currVal_3));
      this._expr_3 = currVal_3;
    }
    this.detectViewChildrenChanges(throwOnChange);
  }
  destroyInternal():void {
    this._RouterLinkWithHref_1_3.ngOnDestroy();
    this._RouterLinkActive_0_3.ngOnDestroy();
  }
  private _handle_click_1_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this._RouterLinkWithHref_1_3.onClick($event.button,$event.ctrlKey,$event.metaKey)) !== false);
    return (true && pd_0);
  }
}
function viewFactory_HeaderComponent1(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement):import1.AppView<any> {
  return new _View_HeaderComponent1(viewUtils,parentInjector,declarationEl);
}
class _View_HeaderComponent2 extends import1.AppView<any> {
  _el_0:any;
  _RouterLinkActive_0_3:import14.RouterLinkActive;
  _query_RouterLink_0_0:import15.QueryList<any>;
  _query_RouterLinkWithHref_0_1:import15.QueryList<any>;
  _el_1:any;
  _RouterLinkWithHref_1_3:import13.RouterLinkWithHref;
  _text_2:any;
  /*private*/ _expr_0:any;
  _arr_0:any;
  /*private*/ _expr_2:any;
  /*private*/ _expr_3:any;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement) {
    super(_View_HeaderComponent2,renderType_HeaderComponent,import6.ViewType.EMBEDDED,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import2.AppElement {
    this._el_0 = this.renderer.createElement((null as any),'li',(null as any));
    this.renderer.setElementAttribute(this._el_0,'routerLinkActive','active');
    this._RouterLinkActive_0_3 = new import14.RouterLinkActive(this.parent.parentInjector.get(import8.Router),new import19.ElementRef(this._el_0),this.renderer);
    this._query_RouterLink_0_0 = new import15.QueryList<any>();
    this._query_RouterLinkWithHref_0_1 = new import15.QueryList<any>();
    this._el_1 = this.renderer.createElement(this._el_0,'a',(null as any));
    this._RouterLinkWithHref_1_3 = new import13.RouterLinkWithHref(this.parent.parentInjector.get(import8.Router),this.parent.parentInjector.get(import17.ActivatedRoute),this.parent.parentInjector.get(import18.LocationStrategy));
    this._text_2 = this.renderer.createText(this._el_1,'Signup',(null as any));
    this._expr_0 = import7.UNINITIALIZED;
    var disposable_0:Function = this.renderer.listen(this._el_1,'click',this.eventHandler(this._handle_click_1_0.bind(this)));
    this._arr_0 = import4.pureProxy1((p0:any):any[] => {
      return [p0];
    });
    this._expr_2 = import7.UNINITIALIZED;
    this._expr_3 = import7.UNINITIALIZED;
    this.init([].concat([this._el_0]),[
      this._el_0,
      this._el_1,
      this._text_2
    ]
    ,[disposable_0],[]);
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import13.RouterLinkWithHref) && ((1 <= requestNodeIndex) && (requestNodeIndex <= 2)))) { return this._RouterLinkWithHref_1_3; }
    if (((token === import14.RouterLinkActive) && ((0 <= requestNodeIndex) && (requestNodeIndex <= 2)))) { return this._RouterLinkActive_0_3; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    var changes:{[key: string]:import7.SimpleChange} = (null as any);
    changes = (null as any);
    const currVal_0:any = 'active';
    if (import4.checkBinding(throwOnChange,this._expr_0,currVal_0)) {
      this._RouterLinkActive_0_3.routerLinkActive = currVal_0;
      if ((changes === (null as any))) { (changes = {}); }
      changes['routerLinkActive'] = new import7.SimpleChange(this._expr_0,currVal_0);
      this._expr_0 = currVal_0;
    }
    if ((changes !== (null as any))) { this._RouterLinkActive_0_3.ngOnChanges(changes); }
    changes = (null as any);
    const currVal_2:any = this._arr_0('signup');
    if (import4.checkBinding(throwOnChange,this._expr_2,currVal_2)) {
      this._RouterLinkWithHref_1_3.routerLink = currVal_2;
      if ((changes === (null as any))) { (changes = {}); }
      changes['routerLink'] = new import7.SimpleChange(this._expr_2,currVal_2);
      this._expr_2 = currVal_2;
    }
    if ((changes !== (null as any))) { this._RouterLinkWithHref_1_3.ngOnChanges(changes); }
    this.detectContentChildrenChanges(throwOnChange);
    if (!throwOnChange) {
      if (this._query_RouterLink_0_0.dirty) {
        this._query_RouterLink_0_0.reset([]);
        this._RouterLinkActive_0_3.links = this._query_RouterLink_0_0;
        this._query_RouterLink_0_0.notifyOnChanges();
      }
      if (this._query_RouterLinkWithHref_0_1.dirty) {
        this._query_RouterLinkWithHref_0_1.reset([this._RouterLinkWithHref_1_3]);
        this._RouterLinkActive_0_3.linksWithHrefs = this._query_RouterLinkWithHref_0_1;
        this._query_RouterLinkWithHref_0_1.notifyOnChanges();
      }
      if ((this.numberOfChecks === 0)) { this._RouterLinkActive_0_3.ngAfterContentInit(); }
    }
    const currVal_3:any = this._RouterLinkWithHref_1_3.href;
    if (import4.checkBinding(throwOnChange,this._expr_3,currVal_3)) {
      this.renderer.setElementProperty(this._el_1,'href',this.viewUtils.sanitizer.sanitize(import21.SecurityContext.URL,currVal_3));
      this._expr_3 = currVal_3;
    }
    this.detectViewChildrenChanges(throwOnChange);
  }
  destroyInternal():void {
    this._RouterLinkWithHref_1_3.ngOnDestroy();
    this._RouterLinkActive_0_3.ngOnDestroy();
  }
  private _handle_click_1_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this._RouterLinkWithHref_1_3.onClick($event.button,$event.ctrlKey,$event.metaKey)) !== false);
    return (true && pd_0);
  }
}
function viewFactory_HeaderComponent2(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement):import1.AppView<any> {
  return new _View_HeaderComponent2(viewUtils,parentInjector,declarationEl);
}
class _View_HeaderComponent3 extends import1.AppView<any> {
  _el_0:any;
  _RouterLinkActive_0_3:import14.RouterLinkActive;
  _query_RouterLink_0_0:import15.QueryList<any>;
  _query_RouterLinkWithHref_0_1:import15.QueryList<any>;
  _el_1:any;
  _RouterLinkWithHref_1_3:import13.RouterLinkWithHref;
  _text_2:any;
  /*private*/ _expr_0:any;
  _arr_0:any;
  /*private*/ _expr_3:any;
  /*private*/ _expr_4:any;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement) {
    super(_View_HeaderComponent3,renderType_HeaderComponent,import6.ViewType.EMBEDDED,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import2.AppElement {
    this._el_0 = this.renderer.createElement((null as any),'li',(null as any));
    this.renderer.setElementAttribute(this._el_0,'routerLinkActive','active');
    this._RouterLinkActive_0_3 = new import14.RouterLinkActive(this.parent.parentInjector.get(import8.Router),new import19.ElementRef(this._el_0),this.renderer);
    this._query_RouterLink_0_0 = new import15.QueryList<any>();
    this._query_RouterLinkWithHref_0_1 = new import15.QueryList<any>();
    this._el_1 = this.renderer.createElement(this._el_0,'a',(null as any));
    this._RouterLinkWithHref_1_3 = new import13.RouterLinkWithHref(this.parent.parentInjector.get(import8.Router),this.parent.parentInjector.get(import17.ActivatedRoute),this.parent.parentInjector.get(import18.LocationStrategy));
    this._text_2 = this.renderer.createText(this._el_1,'Logout',(null as any));
    this._expr_0 = import7.UNINITIALIZED;
    var disposable_0:Function = this.renderer.listen(this._el_1,'click',this.eventHandler(this._handle_click_1_0.bind(this)));
    this._arr_0 = import4.pureProxy1((p0:any):any[] => {
      return [p0];
    });
    this._expr_3 = import7.UNINITIALIZED;
    this._expr_4 = import7.UNINITIALIZED;
    this.init([].concat([this._el_0]),[
      this._el_0,
      this._el_1,
      this._text_2
    ]
    ,[disposable_0],[]);
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import13.RouterLinkWithHref) && ((1 <= requestNodeIndex) && (requestNodeIndex <= 2)))) { return this._RouterLinkWithHref_1_3; }
    if (((token === import14.RouterLinkActive) && ((0 <= requestNodeIndex) && (requestNodeIndex <= 2)))) { return this._RouterLinkActive_0_3; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    var changes:{[key: string]:import7.SimpleChange} = (null as any);
    changes = (null as any);
    const currVal_0:any = 'active';
    if (import4.checkBinding(throwOnChange,this._expr_0,currVal_0)) {
      this._RouterLinkActive_0_3.routerLinkActive = currVal_0;
      if ((changes === (null as any))) { (changes = {}); }
      changes['routerLinkActive'] = new import7.SimpleChange(this._expr_0,currVal_0);
      this._expr_0 = currVal_0;
    }
    if ((changes !== (null as any))) { this._RouterLinkActive_0_3.ngOnChanges(changes); }
    changes = (null as any);
    const currVal_3:any = this._arr_0('logout');
    if (import4.checkBinding(throwOnChange,this._expr_3,currVal_3)) {
      this._RouterLinkWithHref_1_3.routerLink = currVal_3;
      if ((changes === (null as any))) { (changes = {}); }
      changes['routerLink'] = new import7.SimpleChange(this._expr_3,currVal_3);
      this._expr_3 = currVal_3;
    }
    if ((changes !== (null as any))) { this._RouterLinkWithHref_1_3.ngOnChanges(changes); }
    this.detectContentChildrenChanges(throwOnChange);
    if (!throwOnChange) {
      if (this._query_RouterLink_0_0.dirty) {
        this._query_RouterLink_0_0.reset([]);
        this._RouterLinkActive_0_3.links = this._query_RouterLink_0_0;
        this._query_RouterLink_0_0.notifyOnChanges();
      }
      if (this._query_RouterLinkWithHref_0_1.dirty) {
        this._query_RouterLinkWithHref_0_1.reset([this._RouterLinkWithHref_1_3]);
        this._RouterLinkActive_0_3.linksWithHrefs = this._query_RouterLinkWithHref_0_1;
        this._query_RouterLinkWithHref_0_1.notifyOnChanges();
      }
      if ((this.numberOfChecks === 0)) { this._RouterLinkActive_0_3.ngAfterContentInit(); }
    }
    const currVal_4:any = this._RouterLinkWithHref_1_3.href;
    if (import4.checkBinding(throwOnChange,this._expr_4,currVal_4)) {
      this.renderer.setElementProperty(this._el_1,'href',this.viewUtils.sanitizer.sanitize(import21.SecurityContext.URL,currVal_4));
      this._expr_4 = currVal_4;
    }
    this.detectViewChildrenChanges(throwOnChange);
  }
  destroyInternal():void {
    this._RouterLinkWithHref_1_3.ngOnDestroy();
    this._RouterLinkActive_0_3.ngOnDestroy();
  }
  private _handle_click_1_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this.parent.context.onLogout()) !== false);
    const pd_1:any = ((<any>this._RouterLinkWithHref_1_3.onClick($event.button,$event.ctrlKey,$event.metaKey)) !== false);
    return ((true && pd_0) && pd_1);
  }
}
function viewFactory_HeaderComponent3(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement):import1.AppView<any> {
  return new _View_HeaderComponent3(viewUtils,parentInjector,declarationEl);
}